# -*- coding: utf-8 -*-
"""Hedge-rule audit, batch B: R06, R08, B05.

Compared each cluster's item texts against the primary source. Carpenter (1885)
was reached in full at Project Gutenberg. Sungenis & Bennett is in copyright; the
archive.org scan could not be searched reliably through the tools available, so the
R06 term counts rest on the earlier search recorded in review/corrections.json and
are flagged as unconfirmed in the note.
"""

HEDGE_B = {

  "R06": dict(
      assessed=True, drifted=True,
      drift_type="unsourced_addition",
      list_phrasing="""Metric tensors Earth-centered. / Fermat with rotating medium. / Gauge freedom equality. / Covariance of tensor math. / Hamiltonian Earth-origin simplicity. / Anthropic coordinate justification. / Variational minimal paths Earth frame. / Light cone tilt reinterpretation. / Symmetry breaking selects Earth. / Noether charges Earth-defined. / Conservation in Earth frame. / Boundary conditions Earth surface. / Gauge choice alters story only. / Renormalization frame Earth lab. / Geodesics drawn from observers.""",
      source_wording="""&ldquo;The system may have a symmetry which matches that of the coordinate system and simplifies the mathematical clutter used in its description&hellip;. Nevertheless, any reasonable coordinate system may be used. The weave pattern of a net does not determine the shape of the objects that are put into it.&rdquo; (<em>Galileo Was Wrong</em> Vol.&nbsp;I, ch.&nbsp;10, &ldquo;General covariance&rdquo;)""",
      note="""<p>The cited source says one thing, and says it correctly: any reasonable coordinate system may be used. What it does not supply is the vocabulary. The full-text search logged in this review&rsquo;s corrections file found no occurrence of <em>Noether</em>, <em>Fermat</em> or <em>light cone</em> in the scanned volume, <em>gauge</em> only as Ron Hatch&rsquo;s clock-rate scale factor, and <em>renormalization</em> only as a complaint about infinities in quantum field theory. Six of the fifteen titles are on that showing not the authors&rsquo; claims at all but names attached to their position by later hands. We could not re-run the search independently: every route open to us either refused the file or returned a truncated view whose silence proves nothing &mdash; and the archive item cited in our own source list is labelled <em>Galileo Was Wrong (2)</em>, not volume&nbsp;I, which should be resolved before the count is leaned on. A second, weaker drift sits inside the first: &ldquo;Anthropic coordinate justification&rdquo; recruits a principle the authors are recorded as attacking, which would make that one item <em>reversed</em>; but Woit, writing on the film <em>The Principle</em>, describes Sungenis as taking anthropic cosmology to support him, so we leave it unsettled. <strong>Our refutation still argues against all fifteen as though the authors had written them.</strong></p>"""),

  "R08": dict(
      assessed=True, drifted=True,
      drift_type="unsourced_addition",
      list_phrasing="""Modern astronomy uses Earth-centered coordinates. / GPS Earth-centered. / Marine sextant geocentric. / Radar ECEF coordinates. / Nav systems Earth-fixed. / Satellite ground tracks Earth-based. / Solar tables geocentric. / GPS Earth-centered corrections. / ECI/ECEF transforms geocentric. / Navigation inertial Earth base. / Barycentric transforms yield observer ephemerides. / Ephemeris time Earth-defined. / Parallax equations Earth start. / Center equals measurement origin. / Metrology standard Earth clocks. / Naked-eye astronomy topocentric. / Geodesy Earth-centered. / WGS84 ECEF. / ITRF Earth crust reference. / Airliner FMS Earth grid. / VOR network Earth bearings. / Great-circle math. / Nautical almanac geocentric. / Drone RTK Earth grid. / LiDAR ECEF. / Seismology Earth-fixed. / Volcano infrasound triangulation. / GNSS pseudorange Earth clocks.""",
      source_wording="""&ldquo;Either coordinate system could be used with equal justification. The two sentences: &lsquo;the sun is at rest and the Earth moves,&rsquo; or &lsquo;the sun moves and the Earth is at rest,&rsquo; would simply mean two different conventions concerning two different coordinate systems.&rdquo; &mdash; quoted by Sungenis &amp; Bennett from Einstein &amp; Infeld, where it stands under a conditional: <em>If this can be done, our difficulties will be over</em> &hellip; the struggle &ldquo;would <em>then</em> be quite meaningless.&rdquo;""",
      note="""<p>The list supplies both halves of the inference. Sungenis and Bennett argue conventionalism &mdash; that the Ptolemy&ndash;Copernicus dispute is about description rather than fact &mdash; and they argue it by quoting Einstein and Infeld, Poincar&eacute; and Bellarmine. They nowhere argue that GPS, WGS&nbsp;84, ITRF, seismic hypocentres or a nautical almanac are <em>evidence</em> that the Earth does not move, and Sungenis&rsquo;s own later restatements of the case reach for the Einstein quotation without naming a single instrument. Twenty-eight technical artefacts have been added to the source&rsquo;s account. The premise that turns them into an argument comes from the page they sit on, which is headed &ldquo;435 Pieces of Evidence The Earth is Not A Spinning Ball&rdquo;; the items themselves are bare noun phrases. Two smaller drifts ride along. The Einstein sentence is conditional in its original &mdash; <em>if</em> the laws can be written for arbitrary frames, the old struggle <em>would then</em> be meaningless &mdash; and arrives here unconditioned; and a permission is again doing the work of a proof, the pattern already recorded at R01. <strong>Note where our refutation points.</strong> Its body answers the twenty-eight fragments artefact by artefact; the source&rsquo;s actual claim is met only in the steelman, where the reply is that conventionality of origin is not conventionality of dynamics.</p>"""),

  "B05": dict(
      assessed=True, drifted=True,
      drift_type="scope_widened",
      list_phrasing="""Engineering curvature corrections unnecessary. / Bridges no curvature allowance. / Microwave links flat. / Undersea cables straight. / Pipelines straight. / Railroads negligible curvature. / Highways horizon. / Wind farm layout flat. / Tunnel breakthroughs align. / Power line sag flat. / Microwave Fresnel zone flat. / Aerial refueling flat line.""",
      source_wording="""&ldquo;Surveyors&rsquo; operations in the construction of railroads, tunnels, or canals are conducted without the slightest &lsquo;allowance&rsquo; being made for &lsquo;curvature,&rsquo; although it is taught that this so-called allowance is absolutely necessary! This is a cutting proof that Earth is not a globe.&rdquo; (proof&nbsp;3) &mdash; and at proof&nbsp;26 Carpenter does the arithmetic himself: the Atlantic &ldquo;would &hellip; curvate downwards, in the 1665 miles across the Atlantic to Newfoundland, according to the astronomers&rsquo; own tables, more than three-hundred miles.&rdquo;""",
      note="""<p>On strength there is no drift, and it should be said plainly: Carpenter is blunter than the list. He asserts flatly that no allowance is made and closes each item with <em>it is a proof that the Earth is not a globe</em>; the list&rsquo;s &ldquo;Railroads negligible curvature&rdquo; is the milder of the two, conceding a curvature Carpenter denied outright. What has moved is scope. His engineering proofs cover surveyors&rsquo; cuttings, canals, railways, tunnels and the Atlantic cable soundings &mdash; the works of 1885 &mdash; and within them the observation is correct: the correction genuinely is not applied. The list carries the same frame into microwave path design, Fresnel-zone clearance, wind-farm layout, power-line sag, aerial refuelling and 57&nbsp;km tunnel breakthroughs. None of those appear in Carpenter, and none in Dubay&rsquo;s intermediate <em>200 Proofs</em>, whose proof&nbsp;7 adds only bridges. They are the point at which the claim stops being a mis-inference from a true observation and becomes simply false, because in an RF link budget the Earth&rsquo;s radius is the dominant term rather than a neglected one. Our refutation is aimed correctly: it answers Carpenter&rsquo;s own case first &mdash; the definition of <em>level</em>, Suez, the balanced back-and-fore sight, Parliament&rsquo;s datum line &mdash; before it reaches the modern items.</p>"""),

}
