# -*- coding: utf-8 -*-
"""
Distinct-argument clusters, with named provenance.

Each cluster records:
  originator      - the person who introduced this argument into the flat-earth
                    or geocentric canon (NOT the person who repeated it)
  originator_work - the specific publication/broadcast it first appears in
  year            - date of that work
  real_source     - where a genuine scientist's real work is being cited, who
                    actually did it (so the reader can go check the original)
  verdict         - six-verdict rubric; "PENDING" where the writeup is not done
"""

# lane codes: A-EXP geocentric experiment | A-REL relativity/coordinates
#             B flat-earth observation | C scriptural | D historical-esoteric
#             E misappropriated astronomy

CLUSTERS = {

# ---------------------------------------------------------------- A-EXP
"A01": dict(lane="A-EXP", name="Michelson–Morley null proves Earth is not moving",
    originator="Walter van der Kamp", originator_work="The Heart of the Matter", year="1968",
    real_source="Michelson & Morley 1887, Am. J. Sci. 34:333",
    verdict="STANDARD PHYSICS",
    note="A null ether-drift result is exactly what special relativity predicts for a moving Earth. Non-discriminating."),

"A02": dict(lane="A-EXP", name="Michelson–Gale / Sagnac interferometry shows a stationary Earth",
    originator="Robert Sungenis & Robert Bennett", originator_work="Galileo Was Wrong, Vol. I", year="2006",
    real_source="Michelson, Gale & Pearson 1925, ApJ 61:140",
    verdict="REFUTED",
    note="MGP predicted a 0.236 fringe shift for a rotating Earth and measured 0.230 ± 0.005. It detected the rotation and returned the rate to ~2%. Cited backwards. Geocentrist Malcolm Bowden concedes the measurement in Journal of Creation 16(2), 2002."),

"A03": dict(lane="A-EXP", name="“Airy's failure” — water-filled telescope shows no Earth motion",
    originator="Walter van der Kamp", originator_work="De Labore Solis: Airy's Failure Reconsidered", year="1988",
    real_source="G. B. Airy 1871, Proc. Roy. Soc. London, pp. 35–39",
    verdict="REFUTED",
    note="CAREFUL CASE. The null is the predicted result — first via Fresnel's dragging coefficient, then via special relativity: aberration depends on relative source-observer velocity, not on a medium downstream of it. The phrase 'Airy's failure' is internal to the movement; Bouw credits van der Kamp with it. Aberration existing at all is itself evidence Earth moves."),

"A04": dict(lane="A-EXP", name="Stellar aberration is optical/parallax, not Earth's motion",
    originator="Walter van der Kamp", originator_work="Bulletin of the Tychonian Society", year="1970s",
    real_source="James Bradley 1729",
    verdict="REFUTED",
    note="Bouw rejected van der Kamp's version and rebuilt the model to keep aberration — an internal contradiction within the movement."),

"A05": dict(lane="A-EXP", name="No measurable stellar parallax",
    originator="Samuel Rowbotham", originator_work="Zetetic Astronomy: Earth Not a Globe (as “Parallax”)", year="1865",
    real_source="Bessel 1838 (61 Cygni, 0.314″); ESA Gaia DR3",
    verdict="REFUTED",
    note="Gaia DR3 publishes parallaxes for ~1.468 billion sources at 0.02–0.03 mas for G<15. Rowbotham took his pseudonym from the thing he denied."),

"A06": dict(lane="A-EXP", name="Foucault pendulum explained by a rotating firmament",
    originator="Robert Sungenis & Robert Bennett", originator_work="Galileo Was Wrong, Vol. I", year="2006",
    real_source="Léon Foucault 1851",
    verdict="STANDARD PHYSICS",
    note="Restates the observation in a rotating-universe frame. Non-discriminating on its own; ruled out in combination with ring-laser gyros and Michelson–Gale."),

"A07": dict(lane="A-EXP", name="Gyroscopes / ring-laser gyros show no Earth rotation",
    originator="Bob Knodel", originator_work="GlobeBusters / Behind the Curve", year="2018",
    real_source="Sagnac 1913; standard ring-laser INS engineering",
    verdict="SELF-CONTRADICTED",
    note="Knodel's own $20,000 ring-laser gyro measured a 15°/hour drift on camera — exactly 360°÷24h. He looked for ways to shield the apparatus rather than accept the result."),

"A08": dict(lane="A-EXP", name="Aircraft don't compensate for spin; east/west flight times symmetric",
    originator="Samuel Rowbotham", originator_work="Earth Not a Globe", year="1865",
    real_source="Inertial navigation systems measure Earth rate on every flight",
    verdict="REFUTED",
    note="Descends from Rowbotham's vertical-projectile argument. The atmosphere co-moves; INS platforms explicitly correct for a ~15°/hr Earth rate."),

"A09": dict(lane="A-EXP", name="Coriolis effects reassigned to a rotating sky or to electromagnetism",
    originator="Robert Sungenis & Robert Bennett", originator_work="Galileo Was Wrong, Vol. I", year="2006",
    real_source="Gaspard-Gustave de Coriolis 1835",
    verdict="STANDARD PHYSICS", note="Frame restatement; adds no prediction the rotating model does not already make."),

"A10": dict(lane="A-EXP", name="No wind/drag from Earth's motion; atmosphere can't co-rotate",
    originator="Samuel Rowbotham", originator_work="Earth Not a Globe", year="1865",
    real_source=None, verdict="REFUTED",
    note="Assumes the atmosphere is not gravitationally bound to the Earth. It is."),

"A11": dict(lane="A-EXP", name="Michelson–Pease–Pearson null result",
    originator="Robert Sungenis & Robert Bennett", originator_work="Galileo Was Wrong, Vol. I", year="2006",
    real_source="Michelson, Pease & Pearson 1929, JOSA 18(3):181",
    verdict="STANDARD PHYSICS",
    note="A high-precision repeat of Michelson–Morley (expected 0.9 fringe, measured 0.01), run by Michelson at Mount Wilson specifically to test Miller. Same non-discriminating status as A01."),

"A12": dict(lane="A-EXP", name="Dayton Miller detected a real aether drift that was suppressed",
    originator="Robert Sungenis & Robert Bennett", originator_work="Galileo Was Wrong, Vol. I", year="2006",
    real_source="Miller 1933, Rev. Mod. Phys. 5:203; Shankland et al. 1955, Rev. Mod. Phys. 27:167",
    verdict="REFUTED",
    note="Shankland et al. re-examined Miller's original data sheets and traced the periodic shifts to reading statistics and local temperature variation. Shankland had been Miller's own student and colleague — which undercuts the cover-up framing."),

"A13": dict(lane="A-EXP", name="No centrifugal effects felt; equatorial bulge has another cause",
    originator="Samuel Rowbotham", originator_work="Earth Not a Globe", year="1865",
    real_source=None, verdict="REFUTED",
    note="Centrifugal acceleration at the equator is ~0.034 m/s², about 0.3% of g — below unaided perception but routinely measured by gravimeters."),

"A14": dict(lane="A-EXP", name="Ballistics and artillery ignore Earth's rotation",
    originator="Samuel Rowbotham", originator_work="Earth Not a Globe", year="1865",
    real_source="Standard long-range fire-control tables",
    verdict="REFUTED",
    note="Long-range gunnery has corrected for Coriolis drift since WWI; naval fire-control computers did it mechanically."),

"A15": dict(lane="A-EXP", name="Torsion balances, gravimeters and pendulum clocks show no variation",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="NOT DEMONSTRATED", note="No specific published measurement is cited by the list."),

"A16": dict(lane="A-EXP", name="High-altitude balloon drift and sun-angle anomalies",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="NOT DEMONSTRATED", note="No dataset cited."),

"A17": dict(lane="A-EXP", name="Conservation-of-momentum paradox for a moving Earth",
    originator="Samuel Rowbotham", originator_work="Earth Not a Globe", year="1865",
    real_source=None, verdict="REFUTED", note="Galilean relativity, established 1632."),

"A18": dict(lane="A-EXP", name="GPS/time-dilation corrections work in an Earth frame",
    originator="Robert Sungenis & Robert Bennett", originator_work="Galileo Was Wrong, Vol. I", year="2006",
    real_source="GPS relativistic clock corrections",
    verdict="STANDARD PHYSICS", note="GPS corrections are computed in an Earth-centred inertial frame precisely because the Earth rotates within it."),

"A19": dict(lane="A-EXP", name="Gyrocompasses are sky-locked, not Earth-locked",
    originator=None, originator_work=None, year=None,
    real_source="Gyrocompass operating principle",
    verdict="SELF-CONTRADICTED", note="A gyrocompass finds true north by sensing Earth's rotation. It cannot function on a non-rotating Earth."),

"A20": dict(lane="A-EXP", name="Lunar laser ranging shows a fixed baseline",
    originator=None, originator_work=None, year=None,
    real_source="Apollo/Lunokhod retroreflector ranging",
    verdict="NOT DEMONSTRATED", note="No measurement cited; LLR data in fact resolve Earth rotation and lunar recession."),

"A21": dict(lane="A-EXP", name="Satellites and geostationary orbits reinterpreted in an Earth-fixed frame",
    originator="Samuel Shenton", originator_work="International Flat Earth Research Society", year="1957",
    real_source=None, verdict="STANDARD PHYSICS",
    note="Shenton's Sputnik line — 'would sailing round the Isle of Wight prove it spherical?' — is the template."),

"A22": dict(lane="A-EXP", name="The sky's daily appearance is equally described by a moving sky",
    originator="Claudius Ptolemy (via the modern movement)", originator_work="Almagest", year="c. 150 CE",
    real_source=None, verdict="STANDARD PHYSICS",
    note="The observation is true and ancient. It is the definition of a non-discriminating claim: both models predict it identically."),

"A23": dict(lane="A-EXP", name="Gravity / the heliocentric mechanism is unproven",
    originator="Wilbur Glenn Voliva", originator_work="Zion sermons & Leaves of Healing", year="1915",
    real_source=None, verdict="REFUTED",
    note="Voliva's 'gravity is a lot of rot.' Cavendish 1798 onward; g measured to nine significant figures."),

"A25": dict(lane="A-EXP", name="Orbital / lunar / ring stability objections",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="NOT DEMONSTRATED", note="Asserted without a stated calculation."),

"A26": dict(lane="A-EXP", name="No orbital acceleration or rotation has ever been directly detected",
    originator="Walter van der Kamp", originator_work="De Labore Solis", year="1988",
    real_source=None, verdict="SELF-CONTRADICTED",
    note="Contradicted by items the list itself includes: Michelson–Gale, Sagnac, ring-laser gyros, stellar aberration, parallax."),

"A27": dict(lane="A-EXP", name="Tides explained by sky/firmament torque",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="NOT DEMONSTRATED", note="No mechanism specified."),

# ---------------------------------------------------------------- A-REL
"R01": dict(lane="A-REL", name="General covariance permits a stationary-Earth frame",
    originator="Walter van der Kamp", originator_work="The Heart of the Matter", year="1968",
    real_source="Einstein, general relativity (1915)",
    verdict="STANDARD PHYSICS",
    note="CAREFUL CASE. The true part must be conceded: you may write physics in any coordinates. But coordinate freedom is not physical rest — in Earth-centred coordinates the rest of the universe acquires enormous fictitious forces, which is the observable difference."),

"R02": dict(lane="A-REL", name="Mach's principle / relational mechanics allows a fixed Earth",
    originator="Robert Sungenis & Robert Bennett", originator_work="Galileo Was Wrong, Vol. I", year="2006",
    real_source="Ernst Mach, The Science of Mechanics (1883)",
    verdict="STANDARD PHYSICS", note="Mach's principle is not a settled part of GR and does not privilege Earth in any case."),

"R03": dict(lane="A-REL", name="No experiment detects absolute motion; only relative motion is observable",
    originator="Walter van der Kamp", originator_work="The Heart of the Matter", year="1968",
    real_source=None, verdict="STANDARD PHYSICS",
    note="Correct, and it cuts both ways: it equally forbids establishing that the Earth is absolutely at rest."),

"R04": dict(lane="A-REL", name="The equivalence principle validates a local rest frame",
    originator="Robert Sungenis & Robert Bennett", originator_work="Galileo Was Wrong, Vol. I", year="2006",
    real_source="Einstein equivalence principle",
    verdict="STANDARD PHYSICS", note="Local, not global. It says nothing about the Earth's state of motion relative to distant matter."),

"R05": dict(lane="A-REL", name="GR admits rotating-universe solutions / frame dragging",
    originator="Robert Sungenis & Robert Bennett", originator_work="Galileo Was Wrong, Vol. I", year="2006",
    real_source="Gödel 1949; Lense–Thirring 1918; Gravity Probe B",
    verdict="MISLEADING", note="Gödel's universe is a mathematical solution incompatible with the observed cosmos. Frame dragging is real and measured — and is far too small to hold the stars in a daily circuit."),

"R06": dict(lane="A-REL", name="Tensor/gauge/coordinate formalism can be written Earth-centred",
    originator="Robert Sungenis & Robert Bennett", originator_work="Galileo Was Wrong, Vol. I", year="2006",
    real_source=None, verdict="STANDARD PHYSICS",
    note="The largest single cluster in the list. Restates coordinate freedom in ~15 different technical vocabularies. All one argument, already answered at R01."),

"R07": dict(lane="A-REL", name="Alternative gravity theories admit geocentric variants",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="NOT DEMONSTRATED", note="No specific variant, paper, or prediction is cited."),

"R08": dict(lane="A-REL", name="Practical systems use Earth-fixed coordinates, therefore Earth is fixed",
    originator="Robert Sungenis & Robert Bennett", originator_work="Galileo Was Wrong, Vol. I", year="2006",
    real_source="WGS84, ITRF, ECEF/ECI, nautical almanacs",
    verdict="MISLEADING",
    note="The second-largest cluster. A reference frame is chosen for convenience — you navigate in the frame you stand in. WGS84 is an Earth-centred model *of an oblate rotating spheroid*; ECI-to-ECEF conversion contains Earth's rotation rate as an explicit term."),

"R09": dict(lane="A-REL", name="Clock synchronisation / one-way light speed is conventional",
    originator=None, originator_work=None, year=None,
    real_source="Reichenbach–Grünbaum conventionality thesis",
    verdict="STANDARD PHYSICS", note="A real and respectable philosophy-of-physics point that has no geocentric consequence."),

"R10": dict(lane="A-REL", name="Quantum observer-defined frames put the observer at the centre",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="MISLEADING", note="Equivocates on 'observer'. Quantum measurement is not about spatial centrality."),

"R11": dict(lane="A-REL", name="No falsifier distinguishes the frames; multiple cosmologies fit the data",
    originator="Gerardus Bouw", originator_work="Geocentricity", year="1992",
    real_source=None, verdict="SELF-CONTRADICTED",
    note="Bouw — the movement's only credentialed astronomer — conceded his model is observationally equivalent to heliocentrism and must therefore be chosen on theological grounds. That concession removes the list's own claim to be scientific evidence."),

"R12": dict(lane="A-REL", name="The Copernican principle is an unproven assumption",
    originator="Robert Sungenis & Robert Bennett", originator_work="The Principle (film)", year="2014",
    real_source="Zhang & Stebbins 2011, PRL 107:041301",
    verdict="REFUTED",
    note="It is not merely assumed — it is tested. The kSZ power spectrum rules out Gpc-scale off-centre void models."),

# ---------------------------------------------------------------- B
"B01": dict(lane="B", name="Water finds its level, therefore the surface is a plane",
    originator="Samuel Rowbotham", originator_work="Zetetic Astronomy", year="1849",
    real_source=None, verdict="REFUTED",
    note="Equivocates on 'level': a level surface is an equipotential surface, which on a rotating spheroid is curved."),

"B02": dict(lane="B", name="The horizon is flat and rises to eye level",
    originator="Samuel Rowbotham", originator_work="Zetetic Astronomy", year="1849",
    real_source=None, verdict="REFUTED", note="Dip of horizon is measurable with a theodolite and grows with altitude."),

"B03": dict(lane="B", name="Bedford Level / laser canal tests show no curvature",
    originator="Samuel Rowbotham", originator_work="Old Bedford Canal trials", year="1838",
    real_source="Wallace 1870; Oldham 1901",
    verdict="REFUTED",
    note="Rowbotham's two-point setup with a near-water sightline is the exact configuration in which refraction produces a false null. Wallace's three-point 1870 repeat and Oldham's 1901 replication both found the curvature. Flat-earthers cite the court voiding the *wager* as if it reversed the *measurement*."),

"B04": dict(lane="B", name="Long-range visibility of ships, lighthouses and towers",
    originator="Samuel Rowbotham", originator_work="Zetetic Astronomy", year="1849",
    real_source=None, verdict="MISLEADING",
    note="Carpenter's proofs 5 and 36 (Cape Hatteras, Chesapeake Bay) reappear as Dubay's 89 and 96. Atmospheric refraction over water routinely extends the visible horizon; Lady Blount's own 1904 photographer recorded the shimmering vapour layer that explains her result."),

"B05": dict(lane="B", name="Engineering makes no curvature allowance (canals, rail, pipelines, bridges)",
    originator="William Carpenter", originator_work="One Hundred Proofs that the Earth Is Not a Globe", year="1885",
    real_source=None, verdict="REFUTED",
    note="Carpenter's proofs 3 and 40 (Suez Canal) reappear as Dubay's 7 and 8. Local works are built to the local equipotential — which *is* the curved surface. Long-baseline works (tunnels, geodetic survey, GNSS) explicitly model the ellipsoid."),

"B06": dict(lane="B", name="Surveyors assume a plane and make no 'allowance'",
    originator="Samuel Rowbotham", originator_work="Zetetic Astronomy", year="1849",
    real_source="Encyclopaedia Britannica article 'Levelling'",
    verdict="SELF-CONTRADICTED",
    note="Rowbotham's own '8 inches per mile squared' is lifted from a surveying text — real arithmetic for the difference between true and apparent level. He quoted the correction and then denied the thing it corrects for."),

"B07": dict(lane="B", name="Refraction is invoked ad hoc to rescue curvature",
    originator="Samuel Rowbotham", originator_work="Zetetic Astronomy", year="1849",
    real_source=None, verdict="MISLEADING",
    note="Refraction is independently measurable, was described before the dispute, and is used in the same form by surveyors who are not arguing about Earth's shape."),

"B08": dict(lane="B", name="Star trails / Polaris fixed / southern circumpolar geometry",
    originator="Eric Dubay", originator_work="200 Proofs Earth Is Not a Spinning Ball", year="2015",
    real_source=None, verdict="REFUTED",
    note="Southern-hemisphere circumpolar star trails around a *southern* pole are impossible on any single-plane model. This is the item the flat model most clearly gets wrong."),

"B09": dict(lane="B", name="Plumb lines are perpendicular everywhere",
    originator="Samuel Rowbotham", originator_work="Earth Not a Globe", year="1865",
    real_source=None, verdict="REFUTED", note="Plumb lines point to the local gravity vector, which converges toward the centre. Measured by deflection-of-the-vertical surveys."),

"B10": dict(lane="B", name="Sun and Moon appear the same size; solar diameter constant",
    originator="Samuel Rowbotham", originator_work="Earth Not a Globe", year="1865",
    real_source=None, verdict="MISLEADING",
    note="Coincidence of angular size is real and well known. Solar angular diameter in fact varies ~3.4% annually — the reason we have both total and annular eclipses."),

"B11": dict(lane="B", name="Radar, LiDAR, photogrammetry and sonar assume a plane",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="MISLEADING", note="All of these run on ellipsoidal datums. Same convenience-frame error as R08."),

"B12": dict(lane="B", name="Polar navigation and dead reckoning imply a dome/disc",
    originator="Charles K. Johnson", originator_work="Flat Earth News", year="1972",
    real_source=None, verdict="REFUTED",
    note="Antarctic circumnavigation and the 24-hour midnight sun are incompatible with any disc model — as Jeran Campanella conceded on the December 2024 'Final Experiment' expedition."),

"B13": dict(lane="B", name="Mirage and optical ducting explain far sightings",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="SELF-CONTRADICTED", note="Conceding an atmospheric optical mechanism concedes the refraction answer the list elsewhere rejects (B07)."),

"B14": dict(lane="B", name="Rocket and balloon footage shows a flat horizon",
    originator="Charles K. Johnson", originator_work="Flat Earth News", year="1972",
    real_source=None, verdict="MISLEADING",
    note="Curvature is below the noise of a wide-angle lens at balloon altitude; the same footage at altitude with a rectilinear lens shows it."),

# ---------------------------------------------------------------- C
"C01": dict(lane="C", name="Proof-texts on an immovable, established Earth",
    originator="William Carpenter", originator_work="One Hundred Proofs (proof 50 onward)", year="1885",
    real_source=None, verdict="UNFALSIFIABLE", note="Outside the testable domain."),
"C02": dict(lane="C", name="Proof-texts on a moving Sun",
    originator="Rob Skiba", originator_work="biblical-cosmology teaching", year="2015",
    real_source=None, verdict="UNFALSIFIABLE",
    note="Outside the testable domain. Reattributed 2026-08-02: Carpenter's 1885 pamphlet "
         "contains exactly ONE scriptural proof (#50, on immovability) and never mentions "
         "Joshua, Habakkuk or Ecclesiastes. The sun-motion proof-text corpus is a later "
         "accretion reaching its present shape in modern thematic compilations."),
"C03": dict(lane="C", name="Proof-texts on foundations and pillars",
    originator="Rob Skiba", originator_work="biblical-cosmology teaching", year="2015",
    real_source=None, verdict="UNFALSIFIABLE", note="Outside the testable domain."),
"C04": dict(lane="C", name="Proof-texts on the firmament / dome",
    originator="Rob Skiba", originator_work="biblical-cosmology teaching", year="2015",
    real_source=None, verdict="UNFALSIFIABLE", note="Outside the testable domain."),
"C05": dict(lane="C", name="Circle, four corners and ends of the Earth",
    originator="Rob Skiba", originator_work="biblical-cosmology teaching", year="2015",
    real_source=None, verdict="SELF-CONTRADICTED",
    note="The list cites both 'four corners' and 'the circle of the Earth' as proofs. They describe different shapes."),
"C06": dict(lane="C", name="Anthropocentric creation / Earth as footstool",
    originator="Wilbur Glenn Voliva", originator_work="Zion sermons", year="1915",
    real_source=None, verdict="UNFALSIFIABLE", note="A theological claim about purpose, not geometry."),
"C07": dict(lane="C", name="Patristic, scholastic and church-tradition affirmation",
    originator="Robert Sungenis", originator_work="Galileo Was Wrong, Vol. III", year="2006",
    real_source=None, verdict="NOT DEMONSTRATED", note="Appeal to authority; also historically contested."),
"C08": dict(lane="C", name="Liturgy, calendar and eastward orientation as cosmology",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="NOT DEMONSTRATED", note="Ritual practice keyed to apparent sky motion is not a measurement of the sky."),
"C09": dict(lane="C", name="Church art and iconography as cosmology",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="UNFALSIFIABLE", note="Devotional imagery is not survey data."),
"C10": dict(lane="C", name="Job 26:7 — 'he hangs the earth on nothing'",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="SELF-CONTRADICTED",
    note="Cited alongside the pillars-and-foundations texts (C03), which say the opposite. The list uses both as proofs."),

# ---------------------------------------------------------------- D
"D01": dict(lane="D", name="All ancient cultures were geocentric",
    originator="Robert Sungenis", originator_work="Galileo Was Wrong, Vol. II", year="2006",
    real_source=None, verdict="NOT DEMONSTRATED",
    note="Appeal to antiquity. Also false in detail: Aristarchus proposed heliocentrism in the 3rd c. BCE, and Eratosthenes measured the Earth's circumference c. 240 BCE."),
"D02": dict(lane="D", name="Named ancient authorities (Plato, Aristotle, Ptolemy, Tycho)",
    originator="Robert Sungenis", originator_work="Galileo Was Wrong, Vol. II", year="2006",
    real_source=None, verdict="NOT DEMONSTRATED",
    note="Every one of them held the Earth to be a *sphere*. Citing them supports geocentrism at best, and actively refutes the flat half of the list."),
"D03": dict(lane="D", name="Geocentric/Ptolemaic models made accurate predictions",
    originator="Robert Sungenis", originator_work="Galileo Was Wrong, Vol. II", year="2006",
    real_source=None, verdict="STANDARD PHYSICS",
    note="True, and the point: they were superseded *by measurement*, not by decree."),
"D04": dict(lane="D", name="Axis mundi / world tree / omphalos symbolism",
    originator="Mircea Eliade (misapplied)", originator_work="The Myth of the Eternal Return", year="1949",
    real_source="Eliade 1949; Guénon, Le Roi du Monde 1927",
    verdict="UNFALSIFIABLE",
    note="Eliade described religious *symbolism*, not geography — and Jonathan Z. Smith showed even the universality claim is a scholarly construct built on a misread of Spencer and Gillen."),
"D05": dict(lane="D", name="Mandala / still-centre symbolism",
    originator="Mircea Eliade (misapplied)", originator_work="Patterns in Comparative Religion", year="1949",
    real_source=None, verdict="UNFALSIFIABLE", note="Symbol resemblance is not measurement."),
"D06": dict(lane="D", name="Hermetic 'as above, so below' / sacred geometry / microcosm",
    originator="William Walker Atkinson (as 'Three Initiates')", originator_work="The Kybalion", year="1908",
    real_source="Emerald Tablet, Arabic recensions c. 750–830 CE",
    verdict="UNFALSIFIABLE",
    note="The maxim is a 12th-c. Latin rendering of an 8th–9th-c. Arabic alchemical text about transmutation, popularised in its modern form by a 1908 Chicago New Thought pamphlet. It is not an Egyptian statement about the shape of the Earth."),
"D07": dict(lane="D", name="Kabbalistic / alchemical / Gnostic / Rosicrucian / Masonic iconography",
    originator="Helena Blavatsky; Manly P. Hall", originator_work="Isis Unveiled (1877); The Secret Teachings of All Ages (1928)", year="1877",
    real_source=None, verdict="UNFALSIFIABLE",
    note="Esoteric interpretive literature. Blavatsky's claimed source text, the 'Book of Dzyan', is regarded by Buddhist-studies scholars as her own invention."),
"D08": dict(lane="D", name="Temple, cathedral and Dendera-zodiac architecture as cosmology",
    originator="Manly P. Hall", originator_work="The Secret Teachings of All Ages", year="1928",
    real_source="Dendera zodiac, Louvre E 13482, dated c. 50 BCE",
    verdict="SELF-CONTRADICTED",
    note="The Dendera ceiling is a late-Ptolemaic *planisphere* incorporating the Babylonian/Greek zodiac — a projection of a spherical sky, and evidence of Hellenistic transmission rather than primordial hidden knowledge."),
"D09": dict(lane="D", name="Geocentric astrology and zodiacal symbolism as evidence",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="UNFALSIFIABLE", note="Astrology is geocentric because it is observational and topocentric, not because the Earth is fixed."),
"D10": dict(lane="D", name="Heliocentrism has occult/masonic roots",
    originator="Marshall Hall", originator_work="The Earth is not Moving", year="1991",
    real_source=None, verdict="NOT DEMONSTRATED",
    note="Genetic fallacy. Where an idea came from is not evidence about whether it is true."),
"D11": dict(lane="D", name="Perception is reliable; the observer defines the centre",
    originator="Samuel Rowbotham", originator_work="Zetetic Astronomy (the zetetic method)", year="1849",
    real_source=None, verdict="NOT DEMONSTRATED",
    note="Rowbotham's founding move — 'observation is real, theory is imaginary'. It is the epistemology the whole genre rests on, and it is the thing actually being defended."),
"D12": dict(lane="D", name="Simplicity / common sense favours a fixed Earth",
    originator="Samuel Rowbotham", originator_work="Zetetic Astronomy", year="1849",
    real_source=None, verdict="NOT DEMONSTRATED", note="Parsimony is not a measurement, and the flat/fixed model is not in fact simpler once it must account for the southern sky."),
"D13": dict(lane="D", name="Meaning, teleology and fine-tuning imply centrality",
    originator="Robert Sungenis", originator_work="The Principle (film)", year="2014",
    real_source=None, verdict="UNFALSIFIABLE", note="A claim about significance, not position."),
"D14": dict(lane="D", name="Dark matter / dark energy / MOND are modern epicycles",
    originator="Robert Sungenis", originator_work="Galileo Was Wrong, Vol. I", year="2006",
    real_source=None, verdict="MISLEADING",
    note="Rhetorically effective and substantively empty: an unexplained residual in a theory is not evidence for a specific alternative, least of all one with no quantitative model."),
"D15": dict(lane="D", name="The Galileo affair was scientific, not religious",
    originator="Robert Sungenis", originator_work="Galileo Was Wrong, Vol. III", year="2006",
    real_source=None, verdict="NOT DEMONSTRATED", note="A history-of-science claim with no bearing on the Earth's motion either way."),
"D16": dict(lane="D", name="World mythologies depict a circling sun or a covering sky",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="UNFALSIFIABLE", note="Myth records how the sky looks, which is not in dispute."),
"D17": dict(lane="D", name="An electromagnetic/toroidal dome centred on Earth",
    originator="Mark Sargent", originator_work="Flat Earth Clues", year="2015",
    real_source="Schumann resonance (real, and a consequence of a spherical cavity)",
    verdict="NOT DEMONSTRATED",
    note="Sargent's enclosed-world model. The Schumann resonance frequency is derived from the Earth-ionosphere cavity treated as a *sphere* of radius 6371 km — the number only comes out right on a globe."),
"D19": dict(lane="D", name="Eclipse and lunar cycles are tuned to human timekeeping",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="UNFALSIFIABLE", note="Saros and Metonic cycles are consequences of orbital periods; the calendars were built to fit them, not the reverse."),

# ---------------------------------------------------------------- E
"E01": dict(lane="E", name="CMB 'Axis of Evil' aligns with Earth / the ecliptic",
    originator="Robert Sungenis & Rick DeLano", originator_work="The Principle (film)", year="2014",
    real_source="Land & Magueijo 2005, PRL 95:071301; de Oliveira-Costa et al. 2004; Schwarz et al. 2004",
    verdict="MISLEADING",
    note="CAREFUL CASE — represent honestly. The alignment is a real, reproducible feature of the data and the significance debate is genuinely open. But Land & Magueijo themselves walked the significance back in 2007 ('no evidence' under Bayesian model comparison for the general model); Planck 2018 VII notes the look-elsewhere effect and finds no corresponding anomaly in polarization. Decisively: the axis aligns with the *ecliptic and the dipole*, which points to a local/systematic origin — i.e. the alignment is evidence the signal may be partly non-cosmological, which is the opposite of what is claimed."),
"E02": dict(lane="E", name="CMB hemispheric asymmetry, Cold Spot, parity and variance anomalies",
    originator="Robert Sungenis & Rick DeLano", originator_work="The Principle (film)", year="2014",
    real_source="Planck 2018 VII, A&A 641:A7; Schwarz et al. 2016, CQG 33:184001",
    verdict="MISLEADING", note="Same status as E01: real features, contested significance, no geocentric implication."),
"E03": dict(lane="E", name="CMB dipole, dark flow and bulk-flow directionality",
    originator="Robert Sungenis & Rick DeLano", originator_work="The Principle (film)", year="2014",
    real_source="Kashlinsky et al. 2008; Planck Int. XIII 2014, A&A 561:A97",
    verdict="REFUTED",
    note="The dipole *is* our motion — 369.82 ± 0.11 km/s, measured. Dark flow was not confirmed: Planck found no detection of bulk flow in any comoving sphere."),
"E04": dict(lane="E", name="Quasar polarization alignment and large quasar groups",
    originator=None, originator_work=None, year=None,
    real_source="Hutsemékers et al. 2005, A&A 441:915; Clowes et al. 2013, MNRAS 429:2910",
    verdict="MISLEADING",
    note="Real, replicated signals with an accepted astrophysical mechanism — black-hole spins align with the filaments they sit in. Preferred directions differ by redshift slice and hemisphere, so there is no single axis through Earth. Nadathur 2013 showed Clowes's algorithm finds Gpc 'structures' in explicitly homogeneous random simulations."),
"E05": dict(lane="E", name="Galaxy spin handedness / hemispheric bias",
    originator=None, originator_work=None, year=None,
    real_source="Longo 2011, PLB 699:224; Patel & Desmond 2024, MNRAS 534:1553",
    verdict="REFUTED",
    note="The nearest thing to settled on this list. Galaxy Zoo found classifier bias; Iye et al. 2021 found a headline 4.0σ result collapsed to 0.29σ once duplicate entries were removed; Patel & Desmond 2024 pooled all public datasets and found consistency with isotropy."),
"E06": dict(lane="E", name="Dwarf-galaxy planes and satellite alignments",
    originator=None, originator_work=None, year=None,
    real_source="Sawala et al. 2023, Nature Astronomy 7:481",
    verdict="MISLEADING", note="A real ΛCDM tension that has substantially deflated; with Gaia proper motions the Milky Way plane looks transient rather than rotation-supported. No geocentric content either way."),
"E07": dict(lane="E", name="Gamma-ray-burst anisotropy",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="NOT DEMONSTRATED", note="No specific result cited."),
"E08": dict(lane="E", name="Pioneer and flyby anomalies are Earth-directed",
    originator=None, originator_work=None, year=None,
    real_source="Anderson et al. 1998, PRL 81:2858; Turyshev et al. 2012, PRL 108:241101",
    verdict="REFUTED",
    note="The Pioneer anomaly was resolved in 2012 — anisotropic thermal recoil. Nature Physics ran the farewell editorial. The flyby anomaly is an unreplicated 1990s Doppler-tracking puzzle with a decade of null results since; it is a navigation problem, not a cosmological one."),
"E09": dict(lane="E", name="Hubble tension shows we are at a special location",
    originator=None, originator_work=None, year=None,
    real_source="Riess et al. 2022, ApJL 934:L7; Kenworthy et al. 2019, ApJ 875:145",
    verdict="MISLEADING",
    note="The local-void reading was tested directly on 1295 supernovae and excluded at 4–5σ. The tension is between two ways of measuring the same number, both of which assume an expanding homogeneous universe."),
"E10": dict(lane="E", name="Zodiacal dust and Kuiper structure show ecliptic symmetry",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="STANDARD PHYSICS", note="Solar-system material lies in the solar-system plane. That is what a solar system is."),
"E11": dict(lane="E", name="The solar-system plane coincides with the CMB axis",
    originator="Robert Sungenis & Rick DeLano", originator_work="The Principle (film)", year="2014",
    real_source=None, verdict="MISLEADING", note="This is the E01 coincidence restated — and it is the strongest available hint that the CMB alignment is a local systematic."),
"E12": dict(lane="E", name="Redshift quantization in concentric shells around Earth",
    originator="Gerardus Bouw", originator_work="Geocentricity", year="1992",
    real_source="Tifft 1976; refuted by 2dF/SDSS surveys",
    verdict="REFUTED", note="Quantization disappeared as sample sizes grew; the effect was an artefact of small, sparse redshift samples."),
"E13": dict(lane="E", name="Supernova dimming, BAO, birefringence and Lyman-alpha anisotropy",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="NOT DEMONSTRATED", note="Named without a stated result or inference."),
"E14": dict(lane="E", name="Solar anomalies (oblateness, neutrinos, apex, barycentre wobble)",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="REFUTED", note="The solar neutrino problem was solved by neutrino oscillation (SNO, 2001; Nobel 2015). The barycentre wobble is a *prediction* of the Sun being orbited by planets."),
"E15": dict(lane="E", name="VLBI, interferometry and Gaia reductions assume an Earth frame",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="MISLEADING",
    note="Same convenience-frame error as R08. VLBI is in fact one of the instruments that *measures* Earth orientation and rotation to microsecond precision."),
"E16": dict(lane="E", name="Meteor, bolide and micrometeor distributions",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="STANDARD PHYSICS", note="Meteor-shower radiants and calendar fixity are consequences of Earth's orbit crossing debris streams — a heliocentric prediction."),
"E17": dict(lane="E", name="Observed isotropy / Earth-centred fields imply we are the centre",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="MISLEADING",
    note="Isotropy is observed from every vantage point in a homogeneous universe — that is the standard result, not an anomaly. The Earth's magnetosphere is Earth-centred because it is the Earth's field."),
"E18": dict(lane="E", name="Solar-system angular-momentum distribution problem",
    originator=None, originator_work=None, year=None, real_source=None,
    verdict="STANDARD PHYSICS", note="A question in planetary-formation theory (magnetic braking, disc transport), not evidence about Earth's motion."),
}
