# -*- coding: utf-8 -*-
"""
Verbatim corpus: the 461-item "proofs" list at withthesun33.com/about-1
(Andy J. Consoli). Retrieved 2026-08-02. Item 461 is truncated in the source.

Extraction was verified by two independent fetches; a spot-checked range
(items 250-275) matched character-for-character across both.
"""

ITEMS = [
 "Michelson–Morley experiment null result.",
 "Michelson–Gale ether drift detection.",
 "Sagnac effect consistent with stationary Earth.",
 "Airy's failure to detect starlight motion.",
 "Lack of stellar parallax in early measurements.",
 "Coriolis effects reinterpreted as rotating heavens.",
 "Stellar aberration optical not mechanical.",
 "Constant stellar angular sizes.",
 "Uniform star distribution in all directions.",
 "Michelson–Pease null rotation detection.",
 "Foucault pendulum explainable by rotating firmament.",
 "Gyroscope anomalies indicating no rotation.",
 "Aircraft navigation not compensating for spin.",
 "Bedford Level and similar flat-water laser tests.",
 "Geostationary satellites fit rotating sky model.",
 "Perfect circular star trails around Polaris.",
 "Polaris constant alignment over millennia.",
 "No aberration variation over centuries.",
 "Gyroscopes stable absent recalibration.",
 "Time dilation explainable without orbital motion.",
 "Ancient cosmologies uniformly geocentric.",
 "Tycho Brahe's hybrid model.",
 "Ptolemaic predictive accuracy.",
 "Church consistency with Scripture.",
 "Pre-Copernican universal geocentrism.",
 "Relativity permits stationary Earth frame.",
 "Mach's principle supports fixed Earth possibility.",
 "Einstein's equivalence of motion.",
 "No experiment proving absolute motion.",
 "Modern astronomy uses Earth-centered coordinates.",
 "Equal apparent size of Sun and Moon.",
 "Celestial sphere rotation about observer.",
 "Planetary retrograde motion fit geocentric math.",
 "Day–night cycle from firmament rotation.",
 "Lunar phases explainable without orbit.",
 "No visible rotation of atmosphere or clouds.",
 "No naked-eye parallax.",
 "Star rotation constant 24 hours.",
 "Precession from dome rotation.",
 "CMB axis aligned with Earth.",
 "Human perception stationary.",
 "Water finds level.",
 "Horizon flat in long-distance views.",
 "Horizon rises to eye level.",
 "Plane flight times consistent with rest Earth.",
 "GPS Earth-centered.",
 "Surveying assumes stationary ground.",
 "Plumb lines perpendicular worldwide.",
 "Atmosphere concentric layers.",
 "Engineering curvature corrections unnecessary.",
 "Relativity allows Earth-centered math.",
 "Indistinguishable rotating universe equivalence.",
 "Conservation of momentum paradox.",
 "No wind drag from 67,000 mph orbit.",
 "Equatorial bulge alternative cause.",
 "Water rotation electromagnetic explanation.",
 "Equivalence principle permits rest frame.",
 "Relativistic coordinates Earth-valid.",
 "Light bending symmetric about Earth.",
 "Redshift symmetry concentric around Earth.",
 "Psalm 93:1 immovable world.",
 "Psalm 104:5 Earth on foundations.",
 "1 Chron 16:30 firmly established world.",
 "Eccles 1:5 sun rises and sets.",
 "Joshua 10:13 sun stood still.",
 "Habakkuk 3:11 sun and moon halted.",
 "Genesis 1:14–18 lights set for Earth.",
 "Job 38:4 Earth's foundation.",
 "Isaiah 45:18 created to be inhabited.",
 "Psalm 19 sun's tabernacle.",
 "Centrality of humanity symbolism.",
 "Firmament as real structure.",
 "Sun as servant light.",
 "Ancient temple as cosmic model.",
 "Divine order centered on man.",
 "Occult roots of heliocentrism.",
 "Early theologians affirmed geocentrism.",
 "Medieval hierarchy centered on Earth.",
 "Sun's circuit divine metaphor.",
 "Observation inherently geocentric.",
 "No empirical distinction of motion.",
 "Heliocentric gravity assumptions unproven.",
 "Simplicity favors geocentrism.",
 "Perception reliable evidence.",
 "Universe ordered around observer.",
 "Dark matter patchwork like epicycles.",
 "Consciousness defines center.",
 "No proof of revolution.",
 "Axis of Evil alignment.",
 "Quasar distribution symmetry.",
 "Cosmic anisotropy Earth-oriented.",
 "Pioneer anomaly Earth-directed.",
 "Angular momentum imbalance.",
 "Planck data Earth preference.",
 "Lunar stability conflict.",
 "Satellite stability Earth-frame.",
 "Constant solar diameter.",
 "Hubble tension observation bias.",
 "Michelson–Morley replications null.",
 "Miller aether drift detections.",
 "Flyby anomalies Earth-centered.",
 "GPS relativity Earth frame.",
 "Inconsistent stellar parallax.",
 "Solar inertial wobble about Earth.",
 "Stable equatorial bulge.",
 "Coriolis equivalence with sky rotation.",
 "Atmospheric coupling unexplained.",
 "High-altitude balloons drift anomaly.",
 "Geostationary satellites reinterpretation.",
 "Flight symmetry east/west.",
 "Horizon tests flat.",
 "Non-rotation gyroscope studies.",
 "Ocean currents electromagnetic.",
 "Artillery stationary calculations.",
 "GPS Sagnac confirmation.",
 "CMB ecliptic alignment.",
 "Quasar alignment with ecliptic.",
 "Relativistic invariance of frame.",
 "All ancient cultures geocentric.",
 "Plato's Timaeus central Earth.",
 "Aristotle's unmoved mover.",
 "Ptolemy's spheres.",
 "Tycho's geo-heliocentric compromise.",
 "Early Church fathers.",
 "Galileo debate empirical not faith.",
 "Temples as world-centers.",
 "Medieval art concentric heavens.",
 "Navigation charts fixed pole.",
 "Mach's inertia explanation.",
 "Einstein admission of equivalence.",
 "No absolute frame.",
 "Equivalence principle validation.",
 "GR geocentric solutions possible.",
 "No orbital acceleration detected.",
 "Inertial frame symmetry.",
 "Quantum observer centrality.",
 "CMB rest frame small velocity.",
 "Solar apex inconsistency.",
 "Sun's circular path daily.",
 "Ecliptic tilt constancy.",
 "Retrograde motion math valid.",
 "Moon's circular orbit.",
 "Constant constellations.",
 "Polaris fixed.",
 "Zodiacal alignment constant.",
 "Planetary planes observer-aligned.",
 "Celestial equator precision.",
 "Sun's declination repetition.",
 "Psalm 19:4–6 sun's course.",
 "Joshua 10 miracle sun stop.",
 "Habakkuk 3 celestial stillness.",
 "Chronicles 16:30 immovable Earth.",
 "Psalm 96:10 fixed Earth.",
 "Genesis 1:14–18 firmament lights.",
 "Job 38 Earth foundation.",
 "Eccles 1:5 sun's circuit.",
 "Isaiah 38 sundial reversal.",
 "Revelation 6:13 stars fall.",
 "Microcosm–macrocosm correspondence.",
 "Axis mundi doctrine.",
 "Hermetic as above so below.",
 "Sacred geometry centered on observer.",
 "Temple cosmology orientation.",
 "Four corners stability symbol.",
 "Kabbalistic Malkuth fixed.",
 "Alchemical fixed Earth.",
 "Geocentric astrology predictive.",
 "Gnostic concentric heavens.",
 "Christian mystic heart-center.",
 "Rosicrucian dome symbolism.",
 "Solar Christ circling soul.",
 "Egyptian Nut and Geb model.",
 "Hindu Mount Meru axis.",
 "Norse Yggdrasil.",
 "Tibetan mandalas still center.",
 "Platonic solid cosmos.",
 "Heaven within mirrors geometry.",
 "Fixed versus volatile elements.",
 "Direct sensory stillness.",
 "No felt centrifugal force.",
 "Simpler moving sky.",
 "Relativity of perception.",
 "Human consciousness defines center.",
 "Fine-tuning favors centrality.",
 "Teleological seasons fit Earth.",
 "Archetypal up/down symmetry.",
 "Infinite universe removes meaning of center.",
 "Axis alignments repeating.",
 "Galaxy spin bias.",
 "Anisotropy toward Earth.",
 "Pioneer/Flyby anomalies repeated.",
 "Solar neutrino problem.",
 "Lunar ranging stability.",
 "Photon spin alignment.",
 "Solar oblateness constancy.",
 "Dust inflow Sun–Earth line.",
 "GRB anisotropy.",
 "Earth heart chakra symbolism.",
 "Zodiac cross rotation around center.",
 "Twelve gates revolving heavens.",
 "Firmament as electromagnetic dome.",
 "Toroidal field centered on Earth.",
 "Schumann resonance planetary pulse.",
 "Toroid sacred geometry nested.",
 "Helios myth sun circling Earth.",
 "Sundial shadow metaphor.",
 "Mystical cosmography observer central.",
 "Lunar ranging fixed baseline.",
 "Eclipse timing by rotating sky.",
 "Seasonal stars via dome.",
 "Constant air pressure bands.",
 "Jet streams sun-driven.",
 "Perfect star circles.",
 "No coriolis coding in drones.",
 "Marine sextant geocentric.",
 "Radar ECEF coordinates.",
 "Flat radar horizon.",
 "Venus transits epicyclic math.",
 "Solar noon symmetry.",
 "Constant solar diameter.",
 "Refraction invoked for curvature.",
 "Repeated long-range visibility.",
 "Surveying plane assumption.",
 "No rotation proof mechanical.",
 "Ring laser gyro corrections.",
 "Fiber Sagnac frame-dependent.",
 "Weather balloons drift anomaly.",
 "Horizon level rocket footage.",
 "Gyrocompass sky-locked.",
 "Stellar scintillation isotropy.",
 "Nav systems Earth-fixed.",
 "Gravimeter constancy.",
 "Tidal nodes sky torque.",
 "Magnetosphere Earth-centered.",
 "Aurora curtains Earth-focused.",
 "Flight times symmetric.",
 "Balloon sun-angle mismatch.",
 "Bolide entry clustering.",
 "Meteor showers calendar-fixed.",
 "Stellar proper motion tiny.",
 "No annual airglow wind.",
 "Micrometeor isotropy.",
 "Solar wind bow shock centered.",
 "Satellite ground tracks Earth-based.",
 "Tidal resonance geocentric.",
 "Equatorial calm belts.",
 "Trade winds sun-driven.",
 "Bird migration sky cues.",
 "Pendulum building sensitivity.",
 "Torsion balance null variation.",
 "Seiche oscillations periodic.",
 "Tidal bores moon visual timing.",
 "Solar tables geocentric.",
 "Analemma lamp artifact.",
 "Sun apparent speed constant.",
 "Atmospheric superrotation contradiction.",
 "No equatorial centrifugal relief.",
 "Ballistics ignore rotation.",
 "Bridges no curvature allowance.",
 "Tower sight lines beyond curve.",
 "Microwave links flat.",
 "Laser canal tests flat.",
 "Mirage optical ducts.",
 "No naked-eye parallax.",
 "Planet brightness epicycles.",
 "Libration perspective optical.",
 "Constellation stability.",
 "Wind bands sun-synced.",
 "Cloud opposite spin.",
 "Ring stability issue.",
 "Lightning frequency sun path.",
 "Any point inertial possible.",
 "GR allows rotating universe.",
 "Lense–Thirring frame dragging.",
 "Mach inertia relation.",
 "Only relative motion observable.",
 "GR coordinate freedom.",
 "Metric tensors Earth-centered.",
 "Null experiments fit rest Earth.",
 "Einstein equations symmetric.",
 "Sagnac proves apparatus rotation.",
 "GPS Earth-centered corrections.",
 "ECI/ECEF transforms geocentric.",
 "Fermat with rotating medium.",
 "Quantum observer-defined frames.",
 "Gauge freedom equality.",
 "Covariance of tensor math.",
 "Cosmological constant fine-tuned Earthward.",
 "Ether stationary proposals.",
 "Scalar–tensor geocentric variants.",
 "Teleparallel GR alternatives.",
 "Coriolis terms transferred to sky.",
 "No falsifier distinguishing frames.",
 "Preferred CMB dipole Earthward.",
 "Relational mechanics fixed Earth.",
 "Hamiltonian Earth-origin simplicity.",
 "Anthropic coordinate justification.",
 "Kinematical equivalence.",
 "Navigation inertial Earth base.",
 "Variational minimal paths Earth frame.",
 "Light cone tilt reinterpretation.",
 "Symmetry breaking selects Earth.",
 "Noether charges Earth-defined.",
 "Conservation in Earth frame.",
 "Boundary conditions Earth surface.",
 "Barycentric transforms yield observer ephemerides.",
 "Ephemeris time Earth-defined.",
 "Parallax equations Earth start.",
 "Center equals measurement origin.",
 "Multiple cosmologies fit data.",
 "Gauge choice alters story only.",
 "Renormalization frame Earth lab.",
 "Synchronization conventions Earth-based.",
 "One-way light speed conventional.",
 "Metrology standard Earth clocks.",
 "Equivalence local labs rest.",
 "No global inertial frame proven.",
 "Horizon problem Earth initial data.",
 "Geodesics drawn from observers.",
 "CMB Axis of Evil.",
 "Quasar polarization alignment.",
 "Large quasar groups ecliptic.",
 "Radio galaxy handedness asymmetry.",
 "Dipole anisotropy exact fit.",
 "Hubble tension location bias.",
 "Cold Spot preferred axis.",
 "Dark flow directionality.",
 "GRB anisotropy.",
 "Galaxy spin hemisphere bias.",
 "Cluster axes ecliptic.",
 "ISW correlations ecliptic-linked.",
 "Zodiacal contamination persistent.",
 "Kinematic SZ ambiguity.",
 "Supernova dimming alternatives.",
 "BAO fits geocentric models.",
 "Cosmic isotropy violations.",
 "Dwarf galaxy planes coherence.",
 "Satellite alignments.",
 "CMB hemispheric power asymmetry.",
 "Low-l multipole ecliptic alignment.",
 "Parity asymmetry.",
 "Variance anomalies.",
 "Kinematic quadrupole debate.",
 "Planck systematics Earthward.",
 "VLBI Earth-fixed.",
 "Interferometry ground assumption.",
 "Gaia reduction flexible.",
 "Zodiacal cloud symmetry.",
 "Kuiper clumps ecliptic.",
 "Dust inflow apex mismatch.",
 "Oort cloud unnecessary.",
 "MOND epicycle analogy.",
 "Dark energy patching.",
 "Copernican principle assumption.",
 "Redshift quantization concentric.",
 "Tully–Fisher scatter direction.",
 "Lyman-alpha anisotropy.",
 "Cosmic birefringence ecliptic.",
 "Radio dipoles ecliptic.",
 "Solar system plane=CMB.",
 "Sun barycenter wobble epicyclic.",
 "Planet spacing harmonics.",
 "Lunar node locks.",
 "Saros cycle human time.",
 "Metonic precision.",
 "Draconic month tuning.",
 "Ancient stone calendars geocentric.",
 "Eclipse paths on Earth.",
 "Naked-eye astronomy topocentric.",
 "Geodesy Earth-centered.",
 "WGS84 ECEF.",
 "ITRF Earth crust reference.",
 "Airliner FMS Earth grid.",
 "INS Earth updates.",
 "VOR network Earth bearings.",
 "Great-circle math.",
 "Nautical almanac geocentric.",
 "Harbor lights flat lines.",
 "Lighthouse visibility.",
 "Undersea cables straight.",
 "Oil rig sightlines.",
 "Leveling equipotential planes.",
 "Hydrology planar.",
 "River grades.",
 "Pipelines straight.",
 "Railroads negligible curvature.",
 "Highways horizon.",
 "Wind farm layout flat.",
 "Drone RTK Earth grid.",
 "Photogrammetry planar.",
 "LiDAR ECEF.",
 "SAR interferometry.",
 "Seismology Earth-fixed.",
 "Volcano infrasound triangulation.",
 "Mining surveys flat.",
 "Architecture plumb/level universal.",
 "Skyscraper vertical stable.",
 "Pendulum clocks stable.",
 "GNSS pseudorange Earth clocks.",
 "Bathymetry sonar straight.",
 "Ship optical range.",
 "Harbor mirage charts.",
 "Tunnel breakthroughs align.",
 "Power line sag flat.",
 "Microwave Fresnel zone flat.",
 "Aerial refueling flat line.",
 "Artillery geocentric mils.",
 "Polar navigation star dome.",
 "Dead reckoning dome compass.",
 "Psalm 75:3 pillars of Earth.",
 "Job 9:6 shaken Earth.",
 "Job 26:7 hangs on nothing.",
 "Proverbs 8:27 compass on face.",
 "Isaiah 40:22 circle of Earth.",
 "1 Sam 2:8 pillars set world.",
 "Psalm 61:2 ends of Earth.",
 "Psalm 19 line through Earth.",
 "Eccles 1:6 wind circuits.",
 "Matthew 5:35 Earth footstool.",
 "Revelation 7:1 four corners.",
 "Revelation 20:8 four quarters.",
 "Joshua 10 moving sun.",
 "Habakkuk 3 stationary heavens.",
 "Tobit 13 dome heaven.",
 "1 Enoch concentric heavens.",
 "Jubilees lights for Earth.",
 "Church Fathers affirm rest.",
 "Scholastics harmonize Aristotle.",
 "Liturgy calendar solar.",
 "Temple as cosmos model.",
 "Sacred east orientation.",
 "Iconography concentric Christ.",
 "Cathedral maps Earth center.",
 "Creation focused on man.",
 "Psalm 19 heavens declare glory.",
 "Christ as “Sun of righteousness” circling mankind.",
 "Stars falling toward Earth imagery in Apocalypse.",
 "Four winds from Earth's corners.",
 "Psalm 104 firmament supporting lights.",
 "Temple architecture mirroring revolving heavens.",
 "Processional worship keyed to sun/moon over Earth.",
 "Sacred calendars anchored to Earth-based observations.",
 "Early catechisms reflecting immovable Earth language.",
 "Medieval sermons describing concentric heavens.",
 "Patristic commentaries on the sun's “course.”",
 "Liturgical eastward orientation assumes sun's path.",
 "Monastic timekeeping by geocentric sky cycles.",
 "Church art: mandorla over Earth-centered cosmos.",
 "Biblical metaphors of “pillars,” “foundations,” “footstool.”",
 "Prophetic visions framed from an Earth-fixed vantage.",
 "Axis mundi symbols (world tree, mountain) worldwide.",
 "Djed pillar / Jachin & Boaz under starry vaults.",
 "Omphalos stones marking the world's navel/center.",
 "Jerusalem/Delphi as “navel of the world” motifs.",
 "Mandalas with still center, rotating periphery.",
 "Dendera zodiac as dome above Earth.",
 "Mithraic iconography mapping stellar rotation.",
 "Rosicrucian temple diagrams: cosmos around sanctum.",
 "Masonic tracing boards beneath starry canopy.",
 "Hermetic altar at the world center (“as above, so below”).",
 "Alchemy: Earth as [truncated in source]",
]

assert len(ITEMS) == 461, f"expected 461 items, got {len(ITEMS)}"
