# -*- coding: utf-8 -*-
"""Batch 1 — calibration batch, written 2026-08-02, one agent per argument.

Three templates exercised deliberately:
  B05  T1-PD          public-domain source (Carpenter 1885), quoted at length
  A02  T2-COPYRIGHT   in-copyright source (Sungenis 2006), <50-word excerpt
  E17  T3-UNATTRIBUTED no traceable source; `passage` is None, `untraceable` explains

Merged into DEEP by scripts/deep.py. Kept separate so hand-written and
agent-written entries stay distinguishable in diffs.
"""

BATCH1 = {

# ───────────────────────────────────────────────────────── T1-PD
"B05": dict(
    verdict_challenge=dict(challenged=False, proposed_verdict=None,
                          reasoning=None),  # backfilled: predates the field
    tldr=("Most engineering works genuinely do not apply a curvature correction, and "
          "Carpenter was right that they don't. But that is exactly what a round Earth "
          "predicts: a “level” surface is defined by gravity, and on a spinning Earth that "
          "surface is curved, so water in a canal settles onto it by itself and the "
          "surveyor's back-and-fore-sight procedure cancels the correction out by design. "
          "Where distance makes it matter, the Earth's radius appears explicitly in the "
          "arithmetic: microwave path clearance, 57 km tunnel breakthroughs, geodetic "
          "survey and GPS all carry it as a number."),
    passage=dict(
        work="WRK-CARPENTER-1885", pd=True,
        locator="proofs 3, 40, 41 and 51 (index headings: “Surveyors' ‘allowance’”, "
                "“Suez Canal—100 miles—level”, “The ‘true level.’—a curve”, “The ‘Standing Order’”)",
        quote="""3. Surveyors' operations in the construction of railroads, tunnels, or canals are conducted without the slightest "allowance" being made for "curvature," although it is taught that this so-called allowance is absolutely necessary! This is a cutting proof that Earth is not a globe.

40. The Suez Canal, which joins the Red Sea with the Mediterranean, is about one hundred miles long; it forms a straight and level surface of water from one end to the other; and no "allowance" for any supposed "curvature" was made in its construction. It is a clear proof that the Earth is not a globe.

41. When astronomers assert that it is "necessary" to make "allowance for curvature" in canal construction, it is, of course, in order that, in their idea, a level cutting may be had for the water. How flagrantly, then, do they contradict themselves when they say that the curved surface of the Earth is a "true level!" What more can they want for a canal than a true level? Since they contradict themselves in such an elementary point as this, it is an evidence that the whole thing is a delusion, and we have a proof that the Earth is not a globe.

51. A "Standing Order" exists in the English Houses of Parliament that, in the cutting of canals, &c., the datum line employed shall be a "horizontal line, which shall be the same throughout the whole length of the work." Now, if the Earth were a globe, this "Order" could not be carried out: but, it is carried out: therefore, it is a proof that the Earth is not a globe.""",
        gloss="""<p>William Carpenter (1830&ndash;1896) emigrated from London to Baltimore and published <em>One Hundred Proofs that the Earth Is Not a Globe</em> there in 1885, dedicating it to the astronomer Richard Proctor as &ldquo;A Challenge to the Johns Hopkins University.&rdquo; It is the earliest numbered proof-list we have identified, and it works by condensing Samuel Rowbotham's sprawling <em>Earth Not a Globe</em> into a hundred one-line items, each closing with the same formula. Four of the hundred are about engineering practice, and they are the ancestor of the whole modern cluster.</p>
<p>Proof 41 is the one worth slowing down for. Carpenter has read the technical definition correctly &mdash; astronomers and surveyors do say the curved surface is the &ldquo;true level&rdquo; &mdash; and he treats that as a self-contradiction rather than as the answer to his own question. Rowbotham had quoted the source directly: in <em>Zetetic Astronomy</em> (1865), immediately before describing the Bedford Level experiment, he reproduces the <em>Encyclop&aelig;dia Britannica</em> article &ldquo;Levelling,&rdquo; including the sentence &ldquo;<em>the curve of the Earth being the true level, and the tangent to it the apparent level</em>,&rdquo; and takes the article's &ldquo;eight inches very nearly &hellip; at one mile's distance&rdquo; as the arithmetic for the rest of the movement. The &ldquo;8 inches per mile squared&rdquo; figure enters flat-earth literature as a quotation from the encyclopaedia entry that defines <em>level</em> as curved.</p>
<p>The line downstream is documented. <strong>Wilbur Glenn Voliva reprinted Carpenter's hundred proofs under his own Zion, Illinois imprint in 1929</strong>, carrying the Victorian list into the twentieth century. Eric Dubay's <em>200 Proofs</em> (2015) reproduces Carpenter's #3 as its #7 and Carpenter's #40 as its #8, with the Victorian phrasing modernised. Dubay names Carpenter elsewhere in the same list; this is descent and adaptation of a shared inheritance. The twelve modern restatements &mdash; pipelines, wind farms, Fresnel zones, aerial refuelling &mdash; are new examples fitted to the same four Victorian frames.</p>"""),
    steelman=dict(
        description="""<p><strong>Surface (weak):</strong> &ldquo;Engineers obviously do allow for curvature &mdash; the claim is just false.&rdquo; This is the reflex answer and it is wrong. Walk onto a highway job, a pipeline right-of-way, a bridge deck or a wind farm and you will find no curvature term anywhere in the setting-out. The reflex answer loses the argument on contact with a working survey crew.</p>
<p><strong>Deeper (true but incomplete):</strong> &ldquo;The works are too short for it to matter.&rdquo; True for most of the twelve modern examples &mdash; over a 400 m transmission-line span the departure from a tangent plane is about 3 mm against a catenary sag of several metres &mdash; but it does not cover the Suez Canal at 164 km, or a 57 km tunnel, or a 50 km microwave hop. And it concedes the wrong thing: it implies curvature is a small nuisance that gets rounded away, when in the cases that matter it is neither small nor rounded away.</p>
<p><strong>Kernel:</strong> Rowbotham identified a real and specific technical fact, and stated it accurately. Early surveying did use &ldquo;forward levelling&rdquo; with an explicit allowance for convexity; the profession abandoned it. His own words: &ldquo;<em>the most eminent engineers abandoned the practice of the old &lsquo;forward levelling&rsquo; and allowing for convexity; and adopted what is now called the &lsquo;double sight&rsquo; or &lsquo;back-and-fore sight&rsquo; method &hellip; for whatever degree of convexity existed, one &lsquo;sight&rsquo; would compensate for the other.</em>&rdquo; That is not a caricature of surveying. It is what surveying does, and still does &mdash; the current NOAA/National Geodetic Survey levelling manual says curvature error &ldquo;<em>can be reduced by making the backsight and foresight distances in each setup nearly equal. If setups are thus balanced, within a tolerance, correction for curvature need not normally be made while leveling.</em>&rdquo; Carpenter and Rowbotham found the right invariant: there exists a single reproducible surface that every work in the world is built to, transferable over any distance by a procedure that never once mentions the shape of the Earth. That surface is real. Their inference &mdash; that a surface needing no curvature term must not be curved &mdash; is the strongest version of this argument, and the version worth answering.</p>""",
        why_it_doesnt_save_claim="""<p>The kernel points the other way, for the same reason Airy's null does. <strong>Cancellation is not absence.</strong> The back-and-fore-sight method cancels curvature because curvature error grows as the square of the sighting distance and is therefore equal on a balanced backsight and foresight, so it subtracts out. On a plane there would be no error to cancel, no reason to balance sights, and no tolerance on the imbalance. The NGS manual specifies a maximum permitted imbalance and gives tables of the combined refraction-and-curvature term to apply when a setup <em>cannot</em> be balanced &mdash; numbers computed from the Earth's radius. The technique cited as evidence for a plane exists only because the surface is curved.</p>
<p>The same structure holds for the surface itself. What the industry is built to is not a plane but an <strong>equipotential surface of the gravity field</strong> &mdash; the surface along which, in NGS's phrasing, &ldquo;<em>there is no change in potential energy</em>.&rdquo; Water finds it without being told to. A spirit bubble finds it. A plumb bob hangs perpendicular to it. It is closed, it wraps the planet, and on a rotating spheroid it is curved. &ldquo;We built it level and it worked&rdquo; is precisely what a curved equipotential predicts; it does not discriminate between the two hypotheses at all. The discriminating cases are the ones where the local trick stops working &mdash; and in every one, the radius reappears as an explicit number.</p>"""),
    refutation="""<p><strong>Start with the word doing all the work.</strong> &ldquo;Level&rdquo; in engineering does not mean &ldquo;flat.&rdquo; It means <em>along a surface of constant gravitational potential</em> &mdash; a surface you can slide along without gaining or losing energy. NGS defines the horizontal exactly that way, with the geoid being the equipotential surface that best fits the Earth. This is not a redefinition invented to rescue a theory; it is the operational definition every levelling instrument physically implements, because a bubble and a plumb line respond to gravity and nothing else. Water in a canal settles onto that surface by itself. So when Carpenter says the Suez Canal &ldquo;forms a straight and level surface of water from one end to the other,&rdquo; he is right about the observation, and the observation is neutral: on a spheroid a free water surface is <em>necessarily</em> an equipotential, and an equipotential is curved. Proof 41 sees the definition, calls it a contradiction, and stops one step short of the resolution.</p>
<p><strong>Why no allowance is made &mdash; the honest answer, and it is in Rowbotham's own book.</strong> Modern differential levelling carries height forward by setting the instrument roughly midway between two rods and reading back then forward. Because curvature error scales as the square of sighting distance, equal distances produce equal errors that cancel on subtraction. NOAA Manual NOS NGS 3 states it plainly: the line of sight &ldquo;would be parallel to the equipotential surface if the gravity field, at each setup, also defined a plane. This is not the case, however, since the gravity field defines a curved surface,&rdquo; and therefore curvature error &ldquo;can be reduced by making the backsight and foresight distances in each setup nearly equal.&rdquo; The correction is not absent from the theory; it is engineered out of the procedure. Where it cannot be &mdash; unbalanced setups on steep ground, reciprocal setups across a river &mdash; the manual supplies numerical tables for it. Rowbotham described this changeover accurately in 1865 and read it as a retreat. It was a refinement.</p>
<p><strong>Suez, specifically.</strong> The canal has <em>no locks</em>: it is a sea-level cut with seawater flowing freely through it, and as opened in 1869 it ran 164 km long and 8 m deep. Now ask what &ldquo;making an allowance for curvature&rdquo; would even mean there. The only geometric alternative to following the water surface is cutting a straight chord between the two ends &mdash; and a 164 km chord dips about <strong>528 m</strong> below the water surface at its midpoint. By Carpenter's own arithmetic it is the same number: 8 inches &times; 102&sup2; = 6,936 ft of drop from the end tangent, of which the chord's mid-sagitta is a quarter, 1,734 ft &asymp; 528 m. So the &ldquo;allowance&rdquo; being demanded would be an allowance to dig a half-kilometre-deep trench in the middle of a canal that is eight metres deep. Nobody proposed it, in 1869 or since, because the water would simply fill it. Not making that allowance is not a finding about the Earth's shape.</p>
<p><strong>Where the correction is explicit, large and load-bearing.</strong> Four places, all checkable.</p>
<p><em>Radio and microwave links.</em> This is the modern list item that fails hardest, because earth curvature is not merely modelled in RF path design, it is the dominant term. ITU-R Recommendation P.530 instructs designers to compute clearance over an <em>effective</em> Earth of radius k&times;R with median k = 4/3, then re-check against the k value exceeded 99.99% of the time, requiring roughly one full first-Fresnel-zone clearance over the highest obstacle. The ITU's own handbook is explicit about what the trick is for: the modified geometry &ldquo;allows engineers to plot direct wave paths as straight lines rather than calculating path curvature explicitly.&rdquo; That is the same move as balanced backsights &mdash; curvature folded into the coordinate frame so the drawing looks straight. The magnitude: on a 50 km hop the mid-path earth bulge is about <strong>37 m</strong> at k = 4/3, while the first Fresnel zone radius at 6 GHz is about 25 m. Design that link on a flat Earth and the bulge swallows the Fresnel zone and the link does not close.</p>
<p><em>Long tunnels.</em> The Gotthard Base Tunnel is 57 km driven from multiple headings; final breakthrough came in with <strong>8 cm transverse and 1 cm vertical deviation</strong>. That is a two-ended prediction test, not an assumption: independent surface networks are propagated down separate shafts and the two headings must meet. Agreement at the centimetre level over 57 km requires the surface control to be reduced on an ellipsoid, with deflection of the vertical accounted for, because a tunnel bored &ldquo;level&rdquo; in the plumb-line sense would be an arc, and one bored straight cannot also be plumb at both ends.</p>
<p><em>Geodesy and GNSS.</em> Every GPS fix ever taken was computed in an Earth-centred, Earth-fixed frame on the WGS 84 ellipsoid, semi-major axis 6&nbsp;378&nbsp;137 m, flattening 1/298.257223563. The receiver reports a height above that ellipsoid and then applies a geoid model to give the orthometric height &mdash; the elevation a spirit level would agree with. The gap between those two numbers reaches tens of metres, and it exists precisely because &ldquo;level&rdquo; and &ldquo;geometrically straight&rdquo; are different surfaces.</p>
<p><strong>The bridges &mdash; stated carefully.</strong> The Metropolitan Transportation Authority says of the Verrazzano-Narrows Bridge that its &ldquo;693 foot high towers are 1 5/8 inches farther apart at their tops than at their bases because the 4,260 foot distance between them made it necessary to compensate for the earth's curvature.&rdquo; The Humber Bridge's towers, over a 1,410 m span, &ldquo;although vertical, are 1.4 inches (36 mm) farther apart at the top than the bottom due to the curvature of the Earth.&rdquo; A defender is entitled to point out that these are <em>design</em> figures. They are &mdash; but note what generates them. Each tower is built <em>plumb</em>, aligned to its own local gravity vector, because a suspension tower must carry its load axially. Plumb lines 1.3 km apart are not parallel. The tower geometry is a consequence of plumbing, which is a direct physical operation, not an imported constant. (Akashi Kaiky&#333; is often cited alongside these two; we found no operator or primary documentation of a curvature figure for it and have left it out.)</p>
<p><strong>The rest of the twelve.</strong> They divide cleanly. Pipelines, highways, wind-farm layouts, power-line sag, short tunnels and aerial refuelling are all short-baseline: over a 400 m conductor span the departure from a tangent plane is 3 mm against metres of catenary sag; two 100 m turbine towers 1 km apart, each plumb, have tops about 16 mm further apart than their bases, well inside foundation tolerance; two tanker aircraft 30 m apart are on the same tangent plane to any precision that matters. Undersea cables are the opposite case: routes are planned and lengths costed along great-circle geodesics with slack allowance, and appear &ldquo;straight&rdquo; only on projections built to make geodesics look straight. Which brings the argument back to Carpenter's proof 51 and Parliament's &ldquo;datum horizontal line.&rdquo; A survey section is a plot of height against distance on a rectangular grid with enormous vertical exaggeration; the flat baseline is the datum, and the datum is the water surface. The flat line across the top of a cable-soundings chart is the geoid. It is drawn flat because it is the reference, not because it was measured to be a plane.</p>""",
    straw_man=dict(
        identified=True,
        detail=("Carpenter's proof 3 targets the claim that a curvature allowance “is absolutely "
                "necessary” in construction generally — a position no engineering authority has "
                "held. The source Rowbotham himself quotes states the opposite: the Encyclopædia "
                "Britannica “Levelling” article gives the correction as distance-dependent and "
                "sets an explicit threshold, i.e. it tells the reader when the term may be "
                "ignored. Modern practice is the same: NOAA Manual NOS NGS 3 says correction for "
                "curvature “need not normally be made while leveling” once sights are balanced. "
                "So the mainstream position — curvature matters as a function of baseline and "
                "instrument geometry, and is engineered out where it can be — is not the position "
                "being refuted. A subtler misrepresentation runs through proofs 41 and 51: they "
                "treat “level” as though standard usage meant “planar”, and treat a drafting datum "
                "on a section drawing as a claim about the physical shape of the ground.")),
    people=["PER-CARPENTER", "PER-ROWBOTHAM", "PER-VOLIVA", "PER-DUBAY"],
    related=["B01", "B03", "B06", "B07", "B09", "B11", "R08"],
    advocate=dict(
        survives=2, preemptive=None,
        best_defense=("You have not shown me a measurement; you have shown me models with the "
                      "radius already inside them. WGS 84 is a fitted ellipsoid you assume before "
                      "processing a single satellite observation. The 4/3 effective-earth factor "
                      "is a correction applied on top of an assumed radius, and its value is "
                      "elastic — under ducting it runs to infinity, so the parameter can be set to "
                      "whatever makes the link budget work. The Gotthard figure is agreement "
                      "between two survey networks reduced using the same ellipsoidal model, so of "
                      "course they agree; consistency inside a model is not a test of it. "
                      "Verrazzano is the clearest case: nobody climbed those towers and measured "
                      "1 5/8 inches. Meanwhile the observations that require no model at all — "
                      "164 km of canal holding water with no locks and no allowance, a levelling "
                      "line closing on itself across a country, a datum line specified by "
                      "Parliament to be the same horizontal line throughout — are what a plane "
                      "predicts, and you rescue them only by redefining “level” to mean “curved.”")),
    sources=[
        dict(label="William Carpenter, One Hundred Proofs that the Earth Is Not a Globe (Baltimore, 1885) — full text, proofs 3, 40, 41, 51",
             url="https://www.gutenberg.org/ebooks/55387"),
        dict(label="Rowbotham, Zetetic Astronomy: Earth Not a Globe! (1865) — the verbatim Encyclopædia Britannica “Levelling” quotation and the “back-and-fore sight” passage",
             url="https://www.gutenberg.org/ebooks/69892"),
        dict(label="NOAA Manual NOS NGS 3, Geodetic Leveling — §3.1 “Curvature”: the gravity field defines a curved surface; balanced sights remove the need for a correction",
             url="https://geodesy.noaa.gov/library/pdfs/NOAA_Manual_NOS_NGS_0003.pdf"),
        dict(label="NOAA National Geodetic Survey, “The Geopotential Surface” — equipotential surfaces, the geoid, and horizontal as motion with no change in potential energy",
             url="https://geodesy.noaa.gov/research/geopotential-datums/geopotential-surface.shtml"),
        dict(label="Recommendation ITU-R P.530-15 — path clearance, k = 4/3 median effective earth radius factor, Fresnel-zone clearance criteria",
             url="https://www.itu.int/dms_pubrec/itu-r/rec/p/R-REC-P.530-15-201309-S!!PDF-E.pdf"),
        dict(label="ITU-R Handbook, Radiowave Propagation for Terrestrial Point-to-Point Links — earth-bulge worked example",
             url="https://www.itu.int/dms_pub/itu-r/opb/hdb/R-HDB-54-2009-OAS-PDF-E.pdf"),
        dict(label="MTA, Verrazzano-Narrows Bridge — towers 1 5/8 inches farther apart at top than base",
             url="https://www.mta.info/agency/bridges-and-tunnels/verrazzano-narrows-bridge"),
        dict(label="Gotthard Base Tunnel — 8 cm transverse and 1 cm vertical deviation at final breakthrough over 57 km",
             url="https://www.tunnel-online.info/en/artikel/tunnel_2010-08_Gotthard_Base_Tunnel_High-accuracy_at_final_breakthrough-1041005.html"),
        dict(label="WGS 84 reference sheet — ellipsoid semi-major axis 6 378 137 m, flattening 1/298.257223563",
             url="https://www.unoosa.org/pdf/icg/2012/template/WGS_84.pdf")]),

# ─────────────────────────────────────────────────── T2-COPYRIGHT
"A02": dict(
    verdict_challenge=dict(challenged=False, proposed_verdict=None,
                          reasoning=None),  # backfilled: predates the field
    tldr=("Michelson–Gale is the one experiment on this entire list that detected something, "
          "and what it detected was the Earth turning. The 1925 paper predicted a fringe "
          "displacement of 0.236 for a rotating Earth and measured 0.230, recovering the "
          "rotation rate to about two per cent. It appears on the list as evidence for a "
          "stationary Earth — but note the scope carefully: it measures rotation only, and "
          "says nothing either way about the Earth's orbit."),
    passage=dict(
        work="WRK-SUNGENIS-2006", pd=False,
        locator="Vol. I, ch. 10 (“Technical and Summary Analysis of Geocentrism”), p. 191, "
                "section “Michelson-Gale Experiment”, under “Summary”",
        quote="Michelson-Gale detected the ether moving past the Earth's surface at 2% of the "
              "rotation speed. While the Michelson-Morley experiment detected no heliocentric "
              "movement, the Michelson-Gale experiment measured either the effect of the Earth's "
              "rotation or the ether's rotation around the Earth.",
        gloss="""<p>These are Robert Sungenis and Robert Bennett's words, from the summary of their Michelson&ndash;Gale section in <em>Galileo Was Wrong: The Church Was Right</em>, Vol. I (2006; 10th ed. 2013). The book is the direct source of the Michelson&ndash;Gale and Sagnac material circulating in modern proof-lists, generally via Walter van der Kamp, who reframed the interferometry results for the Tychonian Society before Sungenis systematised them.</p>
<p>Two features are worth noting before anything else. First, the authors do <em>not</em> misreport the experiment. They state plainly on the same page that &ldquo;unlike the Michelson-Morley experiment, the Michelson-Gale experiment did not produce null results,&rdquo; and that the displacement &ldquo;was closely related to the rotational velocity of the Earth.&rdquo; Second, the sentence quoted here is a <em>disjunction</em>, not an assertion: the experiment measured &ldquo;either the effect of the Earth's rotation <em>or</em> the ether's rotation around the Earth.&rdquo; The argument is about frame ambiguity, not about the instrument reading zero.</p>
<p>What the cited paper actually reports: Michelson, Gale and Pearson, &ldquo;The Effect of the Earth's Rotation on the Velocity of Light, Part II,&rdquo; <em>Astrophysical Journal</em> 61 (1925) 140&ndash;145, ran a light path around a rectangle 2010 ft east&ndash;west by 1113 ft north&ndash;south at latitude 41&deg;46&prime;. They computed the displacement a <em>rotating</em> Earth should produce as 0.236 &plusmn; 0.002 fringes and observed 0.230 &plusmn; 0.005, concluding that &ldquo;the observed and calculated shifts agree within the limits of observational error.&rdquo; The predicted figure is not a free parameter: 4A&Omega;sin&phi;/&lambda;c, with the known sidereal rate &Omega; = 7.292 &times; 10<sup>&minus;5</sup> rad/s and &lambda; &asymp; 570 nm, returns 0.236. The number the apparatus was checked against was the Earth's rotation rate, and it came back.</p>"""),
    steelman=dict(
        description="""<p>The weak version of the criticism &mdash; that they simply misread the paper &mdash; is not available here. They report the positive result, they report its magnitude, and the geocentrist Malcolm Bowden puts the concession in print in a mainstream creationist journal: &ldquo;The 0.46 km/s speed of the rotation of the Earth (at the equator) relative to the aether was measured to within 2% of the known speed&rdquo; (<em>Journal of Creation</em> 16(2), 2002, p. 80). Any rebuttal opening with an accusation that they ignored the fringe shift is answering a claim nobody made.</p>
<p>A better version &mdash; that they conflate rotation with orbital motion &mdash; is true of some downstream list items but not of the source. Sungenis and Bennett's own &ldquo;Claims and Responses&rdquo; section shows they know precisely what quantity was detected; their reply is that &ldquo;it is only the <em>relative</em> rotation between Earth and cosmos that was detected.&rdquo; That is a considered position, not a confusion.</p>
<p>The strongest form is this, and it should be conceded fully. There is a genuine and deep asymmetry in physics between uniform velocity and rotation, and the geocentrist argument has its finger on it. No local experiment can detect uniform translational motion; that is the relativity principle itself, and Michelson&ndash;Morley's null is its evidence. Rotation is different. A Sagnac interferometer, a Foucault pendulum, a mechanical gyroscope and a ring laser all return a frame-independent answer to the question &ldquo;are you turning?&rdquo; Rotation is absolute in a way velocity is not, in Newtonian mechanics (Newton's bucket) and in relativity alike. This was genuinely contentious: Georges Sagnac presented his 1913 result as evidence <em>for</em> a luminiferous medium and <em>against</em> the emerging relativity, and the &ldquo;Sagnac paradox&rdquo; required careful work to resolve. The resolution &mdash; that a rotating frame is non-inertial and admits no global synchronisation, so the Sagnac term is a geometric holonomy of the metric rather than a violation of <em>c</em> &mdash; is correct but was not obvious in advance. They are pointing at a place where the physics really does treat rotation as a thing in itself.</p>""",
        why_it_doesnt_save_claim="""<p>The asymmetry is real, and it runs the wrong way for the claim.</p>
<p>Consider the counterfactual. If rotation were as undetectable as uniform velocity, then &ldquo;the Earth does not rotate&rdquo; would be a permanently safe coordinate choice, immune to any experiment. That is precisely the shelter the general-covariance and no-absolute-motion arguments elsewhere on this list try to build. But the Michelson&ndash;Gale argument abandons that shelter on purpose. It stakes its case on rotation being physically detectable by a local instrument. Once that is granted, the instrument is entitled to give an answer, and the answer is a number: &Omega;sin&phi; at latitude 41&deg;46&prime;, which is the Earth's sidereal rate. You cannot borrow the authority of an absolute-rotation measurement and then decline the reading.</p>
<p>The remaining move, taken explicitly in the source, is to say the absolute rotation belongs to the cosmos rather than to us. Note what that costs. It converts the item from an experimental result into a relabelling that leaves every measured quantity untouched. Nothing in the fringe count changes; nothing new is predicted; no observation is forbidden. It is no longer a proof that the Earth is stationary &mdash; and by their own hedged phrasing the authors do not present it as one. The list items rendering this as &ldquo;Michelson&ndash;Gale ether drift detection&rdquo; and &ldquo;Sagnac effect consistent with stationary Earth&rdquo; are firmer than the source they descend from.</p>
<p>And the relabelling does not generalise. A rotating optical medium is a hypothesis about light. It has no purchase on a swinging pendulum, a deflected air mass, or a spinning mechanical gyroscope, none of which couple to an optical medium at all. To cover those you must promote the claim to &ldquo;the local inertial frame rotates relative to the ground at 15.041&deg; per hour&rdquo; &mdash; which is what &ldquo;the Earth rotates&rdquo; means operationally. At that point the disagreement is about naming, not about the world, and Gerardus Bouw, the movement's only credentialed astronomer, had already reached that conclusion in <em>Geocentricity</em> (1992).</p>"""),
    refutation="""<p><strong>The experiment is a positive detection, and it is the only one of its kind on the list.</strong> Of the roughly one hundred named-experiment items in this family, Michelson&ndash;Gale&ndash;Pearson 1925 is the single case where the apparatus registered a real signal rather than a null. That signal is the Earth's rotation. They laid a closed light path around a rectangle 2010 ft east&ndash;west by 1113 ft north&ndash;south near Clearing, Illinois, at latitude 41&deg;46&prime;, calculated in advance that a rotating Earth would displace the fringes by 0.236 &plusmn; 0.002, and observed 0.230 &plusmn; 0.005. The instrument recovered the known rotation rate to within a couple of per cent, which is why Bowden, writing as a geocentrist, states in print that the figure &ldquo;was measured to within 2% of the known speed.&rdquo;</p>
<p><strong>What the Sagnac effect is, and why it is not an ether detector.</strong> Send two beams in opposite directions around a closed loop of enclosed area <em>A</em>. If the loop rotates with angular velocity &Omega;, the beams do not return together: &Delta;t = 4(<strong>A</strong>&middot;<strong>&Omega;</strong>)/c&sup2;, giving a phase shift proportional to the enclosed area and the rotation rate. The quantity in the formula is the rotation of the apparatus with respect to the local inertial frame. No medium appears in it. The result follows from special relativity, from general relativity, and from a flat-space time-of-flight argument, without any luminiferous medium being assumed. Sungenis and Bennett derive it on the same page and note, accurately, that this result &ldquo;is obtained without explicitly invoking an ether, Lorentz transformations or General Relativity.&rdquo; That is the whole difficulty for the argument: an equation with no ether in it cannot be evidence for an ether. Nor does the effect contradict the invariance of <em>c</em>, which is a statement about local inertial frames; a rotating frame is not one, cannot be globally synchronised, and the Sagnac term is the measure of exactly that failure.</p>
<p><strong>Scope limit, stated plainly.</strong> Because the effect depends on <strong>A</strong>&middot;<strong>&Omega;</strong>, Michelson&ndash;Gale is sensitive to rotation and to nothing else. Uniform translation of the whole apparatus produces no first-order Sagnac shift. This experiment therefore says nothing whatever about whether the Earth orbits the Sun, and should not be presented as refuting geocentrism entire. What it refutes is the proposition that the Earth does not turn on its axis &mdash; one of the two things modern geocentrism asserts, and the one this item was recruited to support. The orbital half is settled by other evidence entirely: stellar parallax, aberration, radial-velocity and timing data.</p>
<p><strong>The escape, and its real strength.</strong> The geocentrist reply is that the medium, or the whole cosmos tied to it, rotates around a stationary Earth once per sidereal day, leaving the relative rotation &mdash; and therefore the fringe shift &mdash; unchanged. Taken against Michelson&ndash;Gale alone, this is unfalsifiable, and it is worth saying so rather than pretending otherwise. An interferometer measures a relative angular velocity and does not carry a label saying which body owns it.</p>
<p><strong>Why it closes in combination.</strong> The escape is tailored to an optical experiment, and the same rotation rate is returned by instruments with no optical content at all. A Foucault pendulum is a mass on a wire. Coriolis deflection governs the circulation of the atmosphere and oceans. A gyrocompass is a spinning flywheel. Each independently yields &Omega; = 7.292 &times; 10<sup>&minus;5</sup> rad/s, 15.041&deg; per hour sidereal &mdash; the value the light ring gave. A hypothesis about a rotating optical medium has no mechanism by which to deflect a pendulum bob or a hurricane. Broadening it until it does means asserting that the local inertial frame itself turns relative to the ground at the sidereal rate, and that assertion is not distinguishable from the ordinary account; it is the ordinary account with the labels exchanged. Note also that the rotating shell in such a model must be tuned to reproduce &Omega; exactly, making it a fit to the measurement rather than a prediction of it.</p>
<p><strong>One of their stated evasions has since expired.</strong> The book's second response to &ldquo;the experiment shows the Earth is rotating&rdquo; is that the 1925 precision &ldquo;could not distinguish a 24-hour solar period from a period 4 minutes shorter.&rdquo; That was a fair point about 1925 instrumentation. It is no longer available. Large ring lasers are the same physics with six orders of magnitude more resolution: the G ring laser at Wettzell tracks Earth's rotation rate below one part in 10<sup>9</sup>, resolving not merely sidereal versus solar but sub-millisecond length-of-day variations and polar motion &mdash; agreeing with independent VLBI determinations of the same wobbles. The four-minute question the source treats as beyond reach is now resolved routinely, by an instrument whose operating equation is the Sagnac formula.</p>
<p><strong>GPS runs on the Earth's rotation being real.</strong> The Sagnac correction in GPS is computed in an Earth-Centred Inertial frame for a structural reason. As Neil Ashby sets out in <em>Relativity in the Global Positioning System</em>, synchronisation &ldquo;is performed in the local inertial frame, or ECI coordinate system,&rdquo; because attempts to synchronise within the rotating Earth-fixed frame are not transitive: &ldquo;path-dependent discrepancies in the rotating frame are thus inescapable.&rdquo; Carrying a synchronisation eastward around the equator and back accumulates a 207.4 ns discrepancy against the starting clock. That number is set by the Earth's rotation rate and the enclosed area; on a non-rotating Earth it would be zero.</p>
<p><strong>The movement's own instruments agree.</strong> In <em>Behind the Curve</em> (2018), Bob Knodel described putting a ring-laser gyroscope to the question: &ldquo;when we turned on that gyroscope we found that we were picking up a drift. A 15 degree per hour drift.&rdquo; That is 360&deg; divided by 24 hours. His response was to look for ways to shield or explain the reading rather than accept it. The instrument was a Sagnac interferometer, the same class of device as Michelson and Gale's, and it gave the same answer at the first attempt.</p>""",
    straw_man=dict(
        identified=True,
        detail=("Two, running in opposite directions. (1) Against the physics: the source's summary "
                "states that Michelson–Gale data “show clearly that c is not a universal constant, "
                "contradicting Special Relativity.” Special relativity does not claim light "
                "traverses a rotating loop in equal times; its invariance postulate concerns local "
                "inertial frames, and a rotating frame is not one. The Sagnac effect is a standard "
                "consequence of relativity, not a counterexample, so the target is a position no "
                "relativist holds. (2) Against the source: the derived list items overstate their "
                "own origin. “Sagnac effect consistent with stationary Earth” presents as settled "
                "what Sungenis and Bennett state as an explicit either/or. Our treatment must be "
                "tested against the book's hedged wording, not the compressed list phrasing, or the "
                "rebuttal answers something the authors did not write.")),
    people=["PER-SUNGENIS", "PER-VANDERKAMP", "PER-BOUW", "PER-KNODEL"],
    related=["A01", "A06", "A07", "A09", "A18", "A19", "A26", "R03", "R11"],
    advocate=dict(
        survives=3,
        best_defense=("We have never disputed the fringe shift. We report it, we report its size, "
                      "and we accept that it agrees with the rotating-Earth calculation to within a "
                      "couple of per cent. The issue is what an interferometer can and cannot tell "
                      "you. The Sagnac formula contains a single angular velocity — the rotation of "
                      "the apparatus relative to the light-carrying frame — and no measurement made "
                      "inside the apparatus can say which of the two bodies owns it. Michelson and "
                      "Gale established that the Earth and the cosmos are in relative rotation. "
                      "That is all they established. Assigning the motion to the Earth rather than "
                      "the heavens is a choice of reference frame, and general relativity is "
                      "explicit that the choice is not forced. Mach saw the point long before us. "
                      "So when you say the experiment measured the Earth's rotation, you are "
                      "reporting your frame convention and calling it a result."),
        preemptive=("Grant the frame point in full, because it is correct as far as it goes, then "
                    "note what it has cost. Three things. First, it is a different claim from the "
                    "one on the list: “no interferometer can uniquely assign the rotation” is "
                    "defensible; “Michelson–Gale shows a stationary Earth” is not, and the source "
                    "itself offers a disjunction instead. Second, the argument cannot be run "
                    "selectively — if the reply is Machian, the rotating cosmos must also account "
                    "for the Foucault pendulum, Coriolis circulation and the mechanical gyrocompass, "
                    "none of which interact with a light-carrying medium; broadened that far it is "
                    "the standard account under another name, with a shell whose angular velocity "
                    "was set by hand to match the number already measured. Third, the specific "
                    "escape offered in the text — that the experiment could not separate a solar "
                    "from a sidereal period — has been closed by later instruments of the same type. "
                    "What remains is a naming dispute, which is where Bouw arrived on his own.")),
    sources=[
        dict(label="Michelson, Gale & Pearson 1925, ApJ 61:140–145 — predicted 0.236 ± 0.002 fringes, observed 0.230 ± 0.005",
             url="https://paulba.no/paper/Michelson_Gale_II.pdf"),
        dict(label="Sungenis & Bennett, Galileo Was Wrong Vol. I — full text; Michelson–Gale and Sagnac sections, ch. 10",
             url="https://archive.org/stream/GalileoWasWrongTheChurchSungenisRobertA.Bennett4276/Galileo%20Was%20Wrong_%20The%20Church%20%20-%20Sungenis,%20Robert%20A.%20&%20Bennett,_4276_djvu.txt"),
        dict(label="Bowden, “A geocentrist replies to ‘Geocentrism and Creation’”, Journal of Creation 16(2), 2002, p. 80 — concedes the rotation speed was measured to within 2%",
             url="https://creation.com/images/pdfs/tj/j16_2/j16_2_79-82.pdf"),
        dict(label="Ashby, “Relativity in the Global Positioning System”, Living Reviews in Relativity 6:1 (2003) — ECI synchronisation; 207.4 ns eastward circumnavigation discrepancy",
             url="https://link.springer.com/article/10.12942/lrr-2003-1"),
        dict(label="Di Virgilio et al., “Overcoming 1 part in 10^9 of Earth angular rotation rate measurement with the G Wettzell data”, EPJ C 82 (2022)",
             url="https://link.springer.com/article/10.1140/epjc/s10052-022-10798-9"),
        dict(label="Newsweek on Behind the Curve (2018) — Knodel's ring-laser gyroscope registering “a 15 degree per hour drift”",
             url="https://www.newsweek.com/behind-curve-netflix-ending-light-experiment-mark-sargent-documentary-movie-1343362"),
        dict(label="Faulkner, “Geocentrism and Creation”, Journal of Creation 15(2), 2001 — the essential difference is a coordinate change from Sun to Earth",
             url="https://creation.com/geocentrism-and-creation"),
        dict(label="Gerardus D. Bouw — PhD astronomy, Case Western Reserve; model observationally equivalent to heliocentrism",
             url="https://en.wikipedia.org/wiki/Gerardus_D._Bouw")]),

# ────────────────────────────────────────────────── T3-UNATTRIBUTED
"E17": dict(
    verdict_challenge=dict(challenged=False, proposed_verdict=None,
                          reasoning=None),  # backfilled: predates the field
    tldr=("Isotropy is what every observer sees in a homogeneous universe, so an astronomer "
          "in a galaxy a billion light-years away would report the same uniformity we do. "
          "Several items in this cluster are simply true and carry no cosmological content: "
          "the Earth's magnetosphere is centred on the Earth because the Earth's core "
          "generates it, and Jupiter's is centred on Jupiter for the same reason. One item "
          "is wrong on its own terms — the naked-eye sky is conspicuously lopsided, which is "
          "why the Milky Way appears as a band."),
    passage=None,
    untraceable="""<p>There is no original to quote. This cluster carries no named author, no publication, and no citation anywhere in the list or in the source material the list draws on. Each of the seven items is a single declarative line &mdash; <em>Magnetosphere Earth-centered</em>, <em>Stellar scintillation isotropy</em> &mdash; with no measurement, no observer, no date, and no reference to a paper.</p>
<p>That is a finding rather than a gap in our records. The seven items are not seven independent observations. They are one idea &mdash; <em>things look the same in every direction around us, therefore we are at the centre</em> &mdash; restated in seven technical vocabularies: cosmology, atmospheric optics, planetary dynamics, space physics. A list assembled this way grows by restatement rather than by citation, and this cluster is a clean example of the mechanism. It contributes seven entries to the running total while contributing one argument, and the seven are not even errors of the same kind, which suggests the grouping was done by surface phrasing rather than by content.</p>
<p>The absence of a source has a practical cost for a review like this one. Where an argument has an identifiable originator we can read what they actually wrote, see which data they had in front of them, and judge whether the downstream restatement distorts them. Here there is nothing to check against, so we can only address the assertions as written &mdash; which risks answering a stronger or weaker version than whoever first wrote the lines had in mind.</p>
<p><strong>An honest note on our own limits:</strong> <em>untraceable</em> here means we did not find a source, not that none exists. Our pass covered the modern geocentric and zetetic literature and the usual downstream compilations. A line this short could have originated in a forum post, a video caption, or a personal site that leaves no searchable trace, and a reader who can point us at an original statement would improve this entry.</p>""",
    steelman=dict(
        description="""<p><strong>Surface (weak).</strong> <em>They do not understand cosmology.</em> Not worth writing down, and on this cluster also inaccurate: three of the seven items describe the Earth's space environment correctly. The problem is not the physics in them, it is what is concluded from it.</p>
<p><strong>Deeper (better, still incomplete).</strong> <em>Isotropy is expected in a homogeneous universe, so it is not evidence of centrality.</em> True, but it argues in a circle if left there, because homogeneity is precisely what is in dispute. Isotropy measured about a single point does <em>not</em> by itself imply homogeneity. A spherically symmetric universe with us near the middle would also look isotropic to us. That is a genuine model &mdash; the Lema&icirc;tre&ndash;Tolman&ndash;Bondi void &mdash; and it was taken seriously enough in the 2000s to be proposed as an alternative to dark energy.</p>
<p><strong>Kernel (strongest).</strong> The observed isotropy is genuinely surprising and does demand explanation. Patches of the microwave sky on opposite sides of us had not been in causal contact at the time the light was released, under ordinary expansion, yet their temperatures agree to about one part in 100,000. Nothing could have equalised them. That is the horizon problem, and it is one of the puzzles that motivated inflationary cosmology. <em>Why does the universe look the same in every direction?</em> is a first-rank question in physics, not a naive one.</p>
<p>The historical half deserves the same concession. <em>We appear to be at the centre</em> was the honest reading of the available data for most of recorded astronomy. The decisive observational test &mdash; stellar parallax &mdash; was not achieved until Bessel measured 61 Cygni in 1838, more than two centuries after Copernicus. Someone writing these seven lines is standing roughly where every careful naked-eye observer stood before the instruments existed. The inference is not stupid. It is the pre-instrumental default, and displacing it took real work.</p>""",
        why_it_doesnt_save_claim="""<p>The kernel points the other way, sharply. The horizon problem is a problem <em>because</em> the isotropy is too good to have been produced by our location. Putting the Earth at the centre of a symmetric void does not explain why two causally disconnected patches match to one part in 100,000; it relocates the puzzle without addressing it, since those patches still never communicated. Inflation is an attempt at a mechanism. Centrality is not a mechanism at all &mdash; it is a restatement of the observation.</p>
<p>That leaves two candidate explanations, and they have been separated by measurement rather than by preference. A radial inhomogeneity large enough to matter would be visible to distant gas clouds sitting off-centre: they would see a dipole in the microwave background and scatter it, producing a first-order kinetic Sunyaev&ndash;Zel'dovich signal in the small-scale power spectrum. Zhang and Stebbins showed the resulting signal would exceed the ACT and SPT upper limits by a wide margin, ruling out the adiabatic void model and confirming the Copernican principle at gigaparsec radial scales. Homogeneity, meanwhile, is not assumed in these surveys but measured: WiggleZ finds the galaxy distribution reaching homogeneity above roughly 70&ndash;80 h<sup>&minus;1</sup> Mpc, and BOSS CMASS gives about 64 h<sup>&minus;1</sup> Mpc.</p>
<p>The steelman also cannot recruit most of the list. The magnetospheric, auroral and bow-shock items are correct statements about the Earth's own magnetic field and contribute nothing to the strongest version of the argument in either direction. The best form of this claim rests on cosmological isotropy alone &mdash; and cosmological isotropy is the part that has been tested.</p>"""),
    refutation="""<p><strong>The core error, stated plainly.</strong> Isotropy means the sky looks statistically the same in every direction. In a universe whose matter is spread uniformly on large scales, that is what <em>every</em> observer sees, everywhere. An astronomer in a galaxy a billion light-years away would draw the same star counts, the same background temperature in all directions, the same recession of distant galaxies on all sides. Observing it here tells you about the universe's texture, not about your address in it. Mark dots on a balloon and inflate it: every dot sees every other receding, and none is the centre, because the surface of a balloon has no centre. Put raisins in rising dough: each sees the others move away in all directions, faster the further they are. Neither picture is about being special.</p>
<p><strong>Which is why isotropy is one half of an argument, not a conclusion.</strong> Isotropy about every point implies homogeneity, as a matter of geometry. We can only measure isotropy about one point, our own, so the standard reasoning is: isotropy here, plus the Copernican principle that our vantage point is not privileged, therefore homogeneity. The claim in this cluster takes the other branch: isotropy about one point, with the Earth genuinely at the centre of a spherically symmetric universe. That branch is a well-posed model, and it was not set aside by assumption. It was tested and failed &mdash; the kinetic Sunyaev&ndash;Zel'dovich power measured by ACT and SPT falls far short of what such a structure requires. In parallel, the scale at which matter becomes homogeneous is measured directly rather than assumed. The Copernican principle earns its place in these papers by surviving a test it could have failed.</p>
<p><strong>First kind of item: local geophysics, correctly described, with no cosmological content.</strong> <em>Magnetosphere Earth-centered</em>, <em>Aurora curtains Earth-focused</em> and <em>Solar wind bow shock centered</em> are true, and nothing in mainstream physics disputes them, because mainstream physics is where they come from. Nearly all of the geomagnetic field originates in the fluid outer core, where convection and rotation drive electric currents &mdash; the geodynamo. The field is centred on the Earth for the same reason a bar magnet's field is centred on the bar magnet. Aurorae follow that field down to the polar regions and form two ovals approximately centred on the magnetic poles. The bow shock is where the supersonic solar wind is abruptly decelerated on meeting that magnetosphere. The equivocation is in the phrase <em>centred on Earth</em>: in one sense it means <em>generated by the Earth</em>, which is correct; in another it means <em>the universe is arranged around the Earth</em>, which is the conclusion drawn. Jupiter has a far larger magnetosphere, centred on Jupiter, with its own aurorae and bow shock &mdash; by this reasoning Jupiter is the centre of the universe. Two details cut against the picture even locally: the magnetosphere is markedly <em>not</em> symmetric, being compressed sunward and drawn into a long tail on the night side, so its shape is dictated by the Sun; and the dipole axis is tilted roughly 10&deg; from the rotation axis.</p>
<p><strong>Second kind: solar-system architecture, which records how the system formed.</strong> <em>Planetary planes observer-aligned</em> is true in the narrow sense that the planets move near one plane and we are in it, but the explanation is formation, not position. A collapsing cloud with any net rotation must flatten into a disc as it contracts, because angular momentum is conserved while material is free to settle along the rotation axis. Planets condense from that disc and inherit its plane. This is not a retrofitted story: ALMA imaged the disc around HL Tauri directly, resolving concentric rings and gaps around a star no more than a million years old. Observers do not sit inside those discs and they are still discs. Two further points settle it: the alignment is not exact &mdash; orbits are inclined by up to about 7&deg; to the ecliptic, and the Sun's own equator is tilted to it &mdash; and the ecliptic is inclined roughly 60&deg; to the plane of the Milky Way, so this plane lines up with nothing on a galactic scale.</p>
<p><strong>Third kind: effects of our own atmosphere, local by definition.</strong> <em>Stellar scintillation isotropy</em> is a statement about air. Turbulence in the Earth's atmosphere distorts arriving wavefronts and makes point sources flicker; the entire field of adaptive optics exists to undo it. Its rough uniformity around the sky is a fact about the atmosphere being a shell we sit at the bottom of. It is also the one genuinely observer-centred item in the cluster, and its centre is the observer rather than the Earth: it changes when you climb a mountain, and disappears entirely above the atmosphere, which is why stars do not twinkle when viewed from orbit.</p>
<p><strong>Fourth: light bending, which is ambiguous, and answers the same way on either reading.</strong> If <em>Light bending symmetric about Earth</em> means atmospheric refraction, the symmetry is about the observer's vertical, because the atmosphere is a spherical shell and each observer stands at the bottom of it &mdash; and even that is only approximate, since near the horizon refraction depends chiefly on the local temperature gradient and becomes strongly variable. If it means gravitational lensing, the symmetry belongs to the mass doing the bending: Einstein rings are centred on the foreground galaxy or cluster, not on the Earth. On both readings the symmetry axis is anchored to something other than the Earth's place in the universe.</p>
<p><strong>Fifth: one item that is straightforwardly false as stated.</strong> <em>Uniform star distribution in all directions</em> can be checked on any clear dark night without equipment, and it fails. The Milky Way is a bright, irregular band across the sky, because star counts climb steeply toward the galactic plane and toward Sagittarius, where we look through the longest column of the disc. The local star distribution is strikingly anisotropic. This is not a modern subtlety: systematic star gauging along and across that band was how eighteenth- and nineteenth-century astronomers worked out that we live inside a flattened system, and the concentration of globular clusters toward Sagittarius later showed we are not at its middle either. Uniformity appears only at scales hundreds of millions of light-years across &mdash; in the galaxy-survey data this argument would have to accept in order to make its own case.</p>
<p><strong>What would actually count, and which way the real anisotropies point.</strong> A central location is not untestable; it makes predictions, which is why the void model could be and was excluded. Meanwhile the anisotropies we do measure work against centrality rather than for it. The dipole in the microwave background shows the solar system moving at roughly 370 km/s relative to the frame in which that radiation is at rest &mdash; what you expect of an ordinary observer carried along by local gravity, and not what you expect of an object sitting at rest at the middle of everything.</p>""",
    straw_man=dict(
        identified=True,
        detail=("The straw man here is on the side of what standard astronomy is portrayed as "
                "saying. The listed items present observed isotropy as an unexplained "
                "embarrassment for mainstream cosmology, when it is a founding prediction of the "
                "standard model and a phenomenon whose fine-grained perfection prompted one of the "
                "major theoretical developments of the last fifty years. Similarly, the three "
                "magnetospheric items are framed as facts cosmology must awkwardly accommodate, "
                "when they are results produced by mainstream geophysics and space physics and "
                "contested by nobody. Answering these accurately means conceding most of the "
                "observations outright and disputing only the inference drawn from them.")),
    people=[],
    related=["R12", "E01", "E02", "E03", "E11", "E18", "E10", "D13", "A22"],
    advocate=dict(
        survives=3,
        best_defense=("I am not claiming a miracle, I am making a point about method. Look at what "
                      "is actually measured rather than what is inferred. The star fields balance "
                      "around us. Light bends symmetrically about us. The planets ride a plane we "
                      "sit in. The magnetic field we live inside is centred on us, the aurorae wrap "
                      "our poles, the solar wind piles into a bow around us. Every one of those is "
                      "an observation. To escape the plain reading of them, cosmology has to add a "
                      "premise nobody has ever observed — that our vantage point is typical. That "
                      "premise is doing all the work. You are preferring an unobservable "
                      "homogeneity to an observed centrality because the alternative sits badly "
                      "with a philosophical commitment made in the sixteenth century."),
        preemptive=("Expect the move from “the Copernican principle is only an assumption” to "
                    "“therefore centrality is equally well supported.” It was an assumption; it "
                    "stopped being one. The specific alternative — the Earth near the centre of a "
                    "gigaparsec-scale spherically symmetric void — makes a checkable prediction: "
                    "off-centre gas clouds would see a CMB dipole and scatter it into a "
                    "first-order kinetic Sunyaev–Zel'dovich signal. ACT and SPT measured that "
                    "spectrum and the required void overshoots the observed limit substantially. "
                    "The homogeneity scale is likewise measured rather than posited. Expect also an "
                    "attempt to make the magnetospheric items carry argumentative weight; they "
                    "cannot, since a magnetosphere centred on its own planet is a fact about that "
                    "planet's core, and Jupiter's is centred on Jupiter.")),
    sources=[
        dict(label="Zhang & Stebbins 2011, PRL 107:041301 — Confirmation of the Copernican principle at Gpc radial scale from the kSZ power spectrum",
             url="https://arxiv.org/abs/1009.3967"),
        dict(label="Scrimgeour et al. 2012, MNRAS 425:116 — WiggleZ: the transition to large-scale cosmic homogeneity",
             url="https://arxiv.org/abs/1205.6812"),
        dict(label="Ntelis et al. 2016 — The homogeneity scale of the universe (BOSS CMASS)",
             url="https://arxiv.org/abs/1607.03418"),
        dict(label="Guth 1981, PRD 23:347 — Inflationary universe: a possible solution to the horizon and flatness problems",
             url="https://ui.adsabs.harvard.edu/abs/1981PhRvD..23..347G/abstract"),
        dict(label="NASA Science — Earth's magnetosphere: the geodynamo, and the Sun-compressed, tail-stretched shape",
             url="https://science.nasa.gov/science-research/earth-science/earths-magnetosphere-protecting-our-planet-from-harmful-space-energy/"),
        dict(label="NOAA Space Weather Prediction Center — Aurora: two ovals approximately centred on the magnetic poles",
             url="https://www.swpc.noaa.gov/phenomena/aurora"),
        dict(label="ESO/ALMA (eso1436) — the protoplanetary disc around HL Tauri, concentric rings and gaps",
             url="https://www.eso.org/public/news/eso1436/"),
        dict(label="ESO — Adaptive optics: atmospheric turbulence is what makes stars twinkle",
             url="https://www.eso.org/public/teles-instr/technology/adaptive_optics/"),
        dict(label="ESA/Hubble — Gravitational lensing: curvature by the lensing mass; source–lens–observer alignment",
             url="https://esahubble.org/wordbank/gravitational-lensing/"),
        dict(label="R. Pogge, Ohio State Astronomy 162 — The Milky Way as a band; globular clusters concentrated toward Sagittarius",
             url="https://www.astronomy.ohio-state.edu/pogge.1/Ast162/Unit4/milkyway.html")]),
}
